<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param-read.proto

namespace GPBMetadata\Proto\Voucher;

class VoucherParamRead
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¸Ñ
&proto/voucher/voucher-param-read.protovoucher_types_read"€
GetUserVoucherRequest
user_id (

voucher_id (
voucher_group_id (
used (
order_id (
s_create_time (
e_create_time	 (
	find_type
 (	
user_voucher_fields (	
voucher_fields (	
order_by (	
size (
page (
user_voucher_ids (
is_paginate (
v_user_type (	
	v_enabled (
end_time_lg (
end_time_le (
start_time_le (
voucher_cate (	
code (	
min_id (
	used_time (
nondiscount_only (
condition_value (
benefit_value (
voucher_name (	
force_primary (
end_time_ge  (

not_in_ids! (
end_time_le2" (
used_time_le# (
used_time_ge$ ("i
GetUserVoucherResponse
code (
msg (	4
data (2&.voucher_types_read.GetUserVoucherData"}
GetUserVoucherData
	page_size (
page (
total_count (1
list (2#.voucher_types_read.UserVoucherData"≤
UserVoucherData

id (
user_id (

voucher_id (
voucher_group_id (

start_time (
end_time (
used (
	used_time (
order_id	 (
source
 (	
version (
create_time (
update_time (0
voucher (2.voucher_types_read.VoucherData"°

VoucherData

voucher_id (
name (	
group_id (
voucher_type (	
voucher_cate (	
	user_type (	

user_level (	
category_list (	

brand_list	 (	
relation_id
 (	
provider_type (	
scope_items_text (	
rate_in_group (
description (	
nondiscount_only (
effect_position (
effect_users (	
seller_support (
condition_value (
benefit_value (
code (	
total_count (

draw_count (

daliy_info (	
count_limited (

used_count (
price (
getable_time (

start_time (
end_time (
expire_days (
expire_today  (
	sold_days! (
	sold_time" (
act_img# (	
enabled$ (

must_grant% (
create_time& (
update_time\' (
max_off_price( (
seller_list) (	
integral* (

skip_links+ (	
activity_list, (	
product_type- (	
product_coverage. (	
support_clearance/ (
discount_ids0 (	
can_use_days1 (
vc_id2 ("
seller_applying_config_ids3 (	
plum_config_ids4 (	
page_ids5 (	
onsale_day_min6 (
onsale_day_max7 (

show_float8 (

can_notify9 (
show_pos: (
op_id; (
version< (
is_show= (

mark_title> (	"}
VoucherJoinGroupData0
voucher (2.voucher_types_read.VoucherData3
group (2$.voucher_types_read.VoucherGroupData"\\
GetUserVoucherJoinGroupRequest

uv_user_id (
vg_voucher_type (
limit ("ä
UserVoucherJoinGroupData9
user_voucher (2#.voucher_types_read.UserVoucherData3
group (2$.voucher_types_read.VoucherGroupData"x
GetUserVoucherJoinGroupResponse
code (
msg (	:
data (2,.voucher_types_read.UserVoucherJoinGroupData"˛
GetVoucherRequest

voucher_id (
voucher_group_id (
code (	
effect_users (	
	user_type (	
enabled (
	find_type (	
order_by (	
fields	 (	
page
 (
size (
is_paginate (

must_grant (
	min_price (
	max_price (
start_getable_time (
end_getable_time (
getable_time_le (	
eq_price (	
is_available_voucher (
group_by (	
show_pos (
start_time_lt (
vc_id (
is_total_count_ge_zero (
	code_like (	
end_time_ge (	
price_gt_zero (
can_use_days (
end_time_zero ("a
GetVoucherResponse
code (
msg (	0
data (2".voucher_types_read.GetVoucherData"u
GetVoucherData
	page_size (
page (
total_count (-
list (2.voucher_types_read.VoucherData"¥
GetVoucherGroupRequest
code (	
group_id (
reject_code (	

start_time (
end_time (
	code_like (	
fields (	
order_by (	
size	 (
page
 (
is_paginate (
	find_type (	
op_id (

department (	
	user_type (	
show_pos ("k
GetVoucherGroupResponse
code (
msg (	5
data (2\'.voucher_types_read.GetVoucherGroupData"
GetVoucherGroupData
	page_size (
page (
total_count (2
list (2$.voucher_types_read.VoucherGroupData"ô
VoucherGroupData

id (
name (	
code (	

group_type (	
	user_type (	

user_level (	
expire_today (
expire_days (
grant_frequency	 (	
count_limited_per_user
 (

start_time (
end_time (
grant_start_time (
grant_end_time (
act_img (	

must_grant (
create_time (
update_time (
effect_users (	
price (
reject_code (	
voucher_type (

department (	
op_id (
show_pos (

mark_title (	"=
GetVoucherBySettingsRequest
code (	
group_id ("u
GetVoucherBySettingsResponse
code (
msg (	:
data (2,.voucher_types_read.GetVoucherBySettingsData"ß
GetVoucherBySettingsData

voucher_id (
code (	
scope_items_text (	
benefit_value (
max_off_price (
	user_type (	
voucher_cate (	
category_list (	

brand_list	 (	
effect_users
 (	
count_limited_per_user (
grant_frequency (	"
GetOneAvailableVoucherRequest"j
GetOneAvailableVoucherResponse
code (
msg (	-
data (2.voucher_types_read.VoucherData"I
%GetSellerBestUnreceivedVoucherRequest
cat_id (
brand_id ("r
&GetSellerBestUnreceivedVoucherResponse
code (
msg (	-
data (2.voucher_types_read.VoucherData"Å
GetVoucherJoinGroupRequest
vg_op_id (	
vg_department (	
vg_start_time_lt (	
vg_end_time_gt (	
v_getable_time_lt (	
	v_enabled (	
vg_voucher_type (	
v_price (	
v_user_type	 (	
order_by
 (	
group_by (	
offset (
limit (
v_ids (
v_codes (	
	vg_fields (	
v_fields (	
v_group_ids ("
GetVoucherJoinGroupResponse
code (
msg (	
total (6
data (2(.voucher_types_read.VoucherJoinGroupData"G
"GetUserVoucherMaxCreateTimeRequest
user_id (
group_id ("Y
#GetUserVoucherMaxCreateTimeResponse
code (
msg (	
max_create_time ("t
 GetBeforeVoucherDrawCountRequest
voucher_ids (
gt_id (
ge_start_time (
le_start_time ("F
%GetBeforeVoucherDrawCountResponseItem

voucher_id (	
c ("á
!GetBeforeVoucherDrawCountResponse
code (
msg (	G
data (29.voucher_types_read.GetBeforeVoucherDrawCountResponseItem")
SellVoucherListRequest
user_id ("å
SellVoucherListResponse
code (
msg (	5
voucher_list (2.voucher_types_read.VoucherData@
voucher_group_list (2$.voucher_types_read.VoucherGroupData>
user_voucher_list (2#.voucher_types_read.UserVoucherData
user_has_reject_codes (	":
GetMerVoucherRequest
	seller_id (
user_id ("i
GetMerVoucherResponse
code (
msg (	5
voucher_list (2.voucher_types_read.VoucherData"[
!GetUserVoucherAllAvailableRequest

scene_type (
	user_type (	
user_id ("Ä
"GetUserVoucherAllAvailableResponse
code (
msg (	?
list (21.voucher_types_read.GetUserVoucherAllAvailableRow"å
GetUserVoucherAllAvailableRow9
user_voucher (2#.voucher_types_read.UserVoucherData0
voucher (2.voucher_types_read.VoucherData"(
GetVoucherByCodeRequest
codes (	"l
GetVoucherByCodeResponse
code (
msg (	5
voucher_list (2.voucher_types_read.VoucherData"4
!PersonalCenterVoucherCountRequest
user_id ("Å
"PersonalCenterVoucherCountResponse
code (
msg (	@
data (22.voucher_types_read.PersonalCenterVoucherCountData"x
PersonalCenterVoucherCountData
to_get_user (
to_get_seller (
unused_user (
unused_seller ("Z
 PersonalCenterVoucherListRequest

scene_type (
	user_type (	
user_id ("z
!PersonalCenterVoucherListResponse
code (
msg (	:
list (2,.voucher_types_read.PersonalCenterVoucherRow"á
PersonalCenterVoucherRow9
user_voucher (2#.voucher_types_read.UserVoucherData0
voucher (2.voucher_types_read.VoucherData"º
MisVoucherGroupListRequest
	user_type (	
voucher_group_id (

department (	
reject_code (	
vg_code (	
vg_name (	
	vg_status (	

voucher_id (
voucher_code	 (	
voucher_name
 (	
seller_list (	
product_type (	
	price_min (
	price_max (
integral_min (
integral_max (
vc_id (
page (
	page_size (
vg_voucher_type (
op_id2 ("§
MisVoucherGroupListResponse
code (
msg (	4
data (2&.voucher_types_read.MisVoucherGroupRow
page (
	page_size (
total_count ("Ä
MisVoucherGroupRow3
group (2$.voucher_types_read.VoucherGroupData5
voucher_list (2.voucher_types_read.VoucherData"I
GetEvaluateResultVoucherRequest
time (
v_total_count_gt ("u
 GetEvaluateResultVoucherResponse
code (
msg (	6
data (2(.voucher_types_read.VoucherJoinGroupData"=
GetSumSaveAmountRequest
user_id (
	group_ids ("g
GetSumSaveAmountResponseItem
sum_max_off_price (	
sum_benefit_value (	
	user_type (	"u
GetSumSaveAmountResponse
code (
msg (	>
data (20.voucher_types_read.GetSumSaveAmountResponseItem"Q
#GetTotalSavedSumBenefitValueRequest
user_id (
voucher_group_ids ("L
$GetTotalSavedSumBenefitValueResponse
code (
msg (		
c (	"à
GetVoucherAndGroupRequest1
voucher (2 .voucher_types_read.VoucherWhere4
group (2%.voucher_types_read.VoucherGroupWhere
voucher_fields (	
group_fields (	
order_by (	
size (
page (
is_paginate (
	find_type	 (	"n
GetVoucherAndGroupResponse
code (
msg (	5
data (2\'.voucher_types_read.VoucherAndGroupData"ç
VoucherWhere

id (
code (	
enabled (
	is_remain (
	user_type (	
getable_time_le (
no_new_user ("|
VoucherGroupWhere

id (
op_id (

department (	
start_time_le (
end_time_ge (
code (	"~
VoucherAndGroupData
page (
size (
total_count (6
list (2(.voucher_types_read.VoucherJoinGroupData"V
GetUserVoucherBySellerRequest
user_id (
seller_user_id (
used ("n
GetUserVoucherBySellerResponse
code (
msg (	1
data (2#.voucher_types_read.UserVoucherData"V
!GetReadBeanExchangeVoucherRequest
	user_type (	
time (
order_by (	"Å
"GetReadBeanExchangeVoucherResponse
code (
msg (	@
data (22.voucher_types_read.GetReadBeanExchangeVoucherData"á
GetReadBeanExchangeVoucherData0
voucher (2.voucher_types_read.VoucherData3
group (2$.voucher_types_read.VoucherGroupData"
GetSellerVoucherRequest"j
GetSellerVoucherResponse
code (
msg (	3
data (2%.voucher_types_read.SellerVoucherData"z
SellerVoucherData0
voucher (2.voucher_types_read.VoucherData3
group (2$.voucher_types_read.VoucherGroupData"3
GetVoucherCodesByLikeRequest
code_prefix (	"I
GetVoucherCodesByLikeResponse
code (
msg (	
codes (	"\\
#GetHasVoucherUserByVidAndUidRequest

voucher_id (
user_id (
ctime_gt ("R
$GetHasVoucherUserByVidAndUidResponse
code (
msg (	
user_id ("#
!GetVoucherListByDailyStockRequest"n
"GetVoucherListByDailyStockResponse
code (
msg (	-
list (2.voucher_types_read.VoucherData"Z
 GetReceivedNewVoucherUserRequest
user_id (
end_time (
create_time ("L
!GetReceivedNewVoucherUserResponse
code (
msg (	
data ("E
GetUserSumBenefitValueRequest

start_time (
end_time ("y
GetUserSumBenefitValueResponse
code (
msg (	<
data (2..voucher_types_read.GetUserSumBenefitValueData"]
GetUserSumBenefitValueData
user_id (
benefit_value (
user_voucher_id ("7
 GetVoucherGroupConfigListRequest
voucher_ids ("r
!GetVoucherGroupConfigListResponse
code (
msg (	2
data (2$.voucher_types_read.VoucherGroupData"L
$GetCountUserVoucherGroupByVIdRequest
user_id (
voucher_ids ("J
)GetCountUserVoucherGroupByVIdResponseItem	
C (

voucher_id ("è
%GetCountUserVoucherGroupByVIdResponse
code (
msg (	K
data (2=.voucher_types_read.GetCountUserVoucherGroupByVIdResponseItem"{
(GetSellerToDescendBindVoucherListRequest
end_time (

begin_time (
current_time (
voucher_ids ("k
-GetSellerToDescendBindVoucherListResponseItem
user_voucher_id (
user_id (
order_id ("ó
)GetSellerToDescendBindVoucherListResponse
code (
msg (	O
data (2A.voucher_types_read.GetSellerToDescendBindVoucherListResponseItem"u
#GetCalPriceVoucherListByTypeRequest
type (
coverage_condition (	

time_point (
is_japan ("p
$GetCalPriceVoucherListByTypeResponse
code (
msg (	-
data (2.voucher_types_read.VoucherData"@
*CheckCalPriceVoucherListByTimePointRequest

time_point ("w
+CheckCalPriceVoucherListByTimePointResponse
code (
msg (	-
data (2.voucher_types_read.VoucherData"O
GetCalPriceVoucherListRequest
coverage_condition (	

time_point ("j
GetCalPriceVoucherListResponse
code (
msg (	-
data (2.voucher_types_read.VoucherData"ï
#GetCalPriceVoucherListByUserRequest
user_id (
coverage_condition (	

time_point (
is_new_user_voucher (
is_japan ("p
$GetCalPriceVoucherListByUserResponse
code (
msg (	-
data (2.voucher_types_read.VoucherData".
GetUserVoucherByOrderIDRequest
oids ("n
GetUserVoucherByOrderIDResponse
code (
msg (	0
list (2".voucher_types_read.UserVoucherRow"*
GetUserVoucherByPidRequest
pids ("j
GetUserVoucherByPidResponse
code (
msg (	0
list (2".voucher_types_read.UserVoucherRow"}
UserVoucherRow9
user_voucher (2#.voucher_types_read.UserVoucherData0
voucher (2.voucher_types_read.VoucherData"0
GetTimeSlotUserSumDataRequest
user_id ("Å
GetTimeSlotUserSumDataResponse
code (
msg (	D
data (26.voucher_types_read.GetTimeSlotUserSumDataResponseData"ö
"GetTimeSlotUserSumDataResponseData
m_yhqzs (	
m_yhqhds (	
m_yhqje (	
	m_syyhqzs (	

m_syyhqhds (	
	m_syyhqje (	
m_qtndqyhqzs (	
m_qtndqyhqje (	
m_swtndqyhqzs	 (	
m_swtndqyhqje
 (	
m_sstndqyhqzs (	
m_sstndqyhqje (	"@
 MisGetWaitExpireSVouchersRequest
stime (
etime ("p
!MisGetWaitExpireSVouchersResponse
code (
msg (	0
data (2".voucher_types_read.UserVoucherRow"@
GetNextVoucherIdRequest

voucher_id (
	group_ids ("I
GetNextVoucherIdResponse
code (
msg (	

voucher_id ("-
GetSumRateInGroupRequest
	group_ids ("Q
GetSumRateInGroupResponse
code (
msg (	
sum_rate_in_group ("W
GetPlumVouchersRequest
	seller_id (	
is_out_living (
is_new_user ("l
GetPlumVouchersResponse
code (
msg (	6
data (2(.voucher_types_read.VoucherJoinGroupData"F
"GetVoucherByCatIdAndBrandIdRequest
cat_id (
brand_id ("o
#GetVoucherByCatIdAndBrandIdResponse
code (
msg (	-
data (2.voucher_types_read.VoucherData"-
GetUnclaimedVoucherRequest
user_id ("g
GetUnclaimedVoucherResponse
code (
msg (	-
list (2.voucher_types_read.VoucherData"8
"GetVoucherStandardConditionRequest

voucher_id ("|
#GetVoucherStandardConditionResponse
code (
msg (	:
data (2,.voucher_types_read.VoucherStandardCondition"Ω
VoucherStandardCondition
category_id (
brand_id (
activity_id (
onsale_day_egt (
onsale_day_elt (
product_type (	
condition_value (
clearance_discount_id (
nondiscount_only	 (:
v_product_range
 (2!.voucher_types_read.VProductRange
	seller_id ("å
VProductRange

range_type (
use_condition_field (	J
condition_fields (20.voucher_types_read.VProductRangeConditionFields"ﬁ
VProductRangeConditionFields
cooperate_type (	
is_activity (
discount_capacity (
provider (	
dispatch_type (	
is_live (
is_self_live (
activity_id (
	seller_id	 (B.Zproto/voucher app\\components\\proto\\voucherbproto3'
        , true);

        static::$is_initialized = true;
    }
}

