<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/order/order.proto

namespace app\components\proto\order;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>order.FullReturnInfo</code>
 */
class FullReturnInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 group_id = 1;</code>
     */
    protected $group_id = 0;
    /**
     *仅记录用,服务端不用该值
     *
     * Generated from protobuf field <code>int64 conf_id = 2;</code>
     */
    protected $conf_id = 0;
    /**
     * 商品
     *
     * Generated from protobuf field <code>repeated .order.FullReturnProductInfo products = 3;</code>
     */
    private $products;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $group_id
     *     @type int|string $conf_id
     *          仅记录用,服务端不用该值
     *     @type \app\components\proto\order\FullReturnProductInfo[]|\Google\Protobuf\Internal\RepeatedField $products
     *           商品
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Order\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 group_id = 1;</code>
     * @return int|string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * Generated from protobuf field <code>int64 group_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->group_id = $var;

        return $this;
    }

    /**
     *仅记录用,服务端不用该值
     *
     * Generated from protobuf field <code>int64 conf_id = 2;</code>
     * @return int|string
     */
    public function getConfId()
    {
        return $this->conf_id;
    }

    /**
     *仅记录用,服务端不用该值
     *
     * Generated from protobuf field <code>int64 conf_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConfId($var)
    {
        GPBUtil::checkInt64($var);
        $this->conf_id = $var;

        return $this;
    }

    /**
     * 商品
     *
     * Generated from protobuf field <code>repeated .order.FullReturnProductInfo products = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProducts()
    {
        return $this->products;
    }

    /**
     * 商品
     *
     * Generated from protobuf field <code>repeated .order.FullReturnProductInfo products = 3;</code>
     * @param \app\components\proto\order\FullReturnProductInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProducts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \app\components\proto\order\FullReturnProductInfo::class);
        $this->products = $arr;

        return $this;
    }

}

