<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/order/order.proto

namespace app\components\proto\order;

use UnexpectedValueException;

/**
 * Protobuf type <code>order.FullReturnRewardType</code>
 */
class FullReturnRewardType
{
    /**
     * Generated from protobuf enum <code>FULL_RETURN_REWARD_TYPE_NONE = 0;</code>
     */
    const FULL_RETURN_REWARD_TYPE_NONE = 0;
    /**
     * 优惠券
     *
     * Generated from protobuf enum <code>FULL_RETURN_REWARD_TYPE_VOUCHER = 1;</code>
     */
    const FULL_RETURN_REWARD_TYPE_VOUCHER = 1;
    /**
     * 红豆
     *
     * Generated from protobuf enum <code>FULL_RETURN_REWARD_TYPE_RED_BEAN = 2;</code>
     */
    const FULL_RETURN_REWARD_TYPE_RED_BEAN = 2;
    /**
     * 红包
     *
     * Generated from protobuf enum <code>FULL_RETURN_REWARD_TYPE_RED_BAG = 3;</code>
     */
    const FULL_RETURN_REWARD_TYPE_RED_BAG = 3;

    private static $valueToName = [
        self::FULL_RETURN_REWARD_TYPE_NONE => 'FULL_RETURN_REWARD_TYPE_NONE',
        self::FULL_RETURN_REWARD_TYPE_VOUCHER => 'FULL_RETURN_REWARD_TYPE_VOUCHER',
        self::FULL_RETURN_REWARD_TYPE_RED_BEAN => 'FULL_RETURN_REWARD_TYPE_RED_BEAN',
        self::FULL_RETURN_REWARD_TYPE_RED_BAG => 'FULL_RETURN_REWARD_TYPE_RED_BAG',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

