<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/order/order.proto

namespace app\components\proto\order;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>order.GetFullReturnRewardFromOrderItemIdRequest</code>
 */
class GetFullReturnRewardFromOrderItemIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 order_item_id = 1;</code>
     */
    protected $order_item_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $order_item_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Order\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 order_item_id = 1;</code>
     * @return int|string
     */
    public function getOrderItemId()
    {
        return $this->order_item_id;
    }

    /**
     * Generated from protobuf field <code>int64 order_item_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderItemId($var)
    {
        GPBUtil::checkInt64($var);
        $this->order_item_id = $var;

        return $this;
    }

}

