<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/order/order.proto

namespace app\components\proto\order;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>order.GetFullReturnRewardFromOrderItemIdResponse</code>
 */
class GetFullReturnRewardFromOrderItemIdResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * 200代表成功; 非200代表失败
     *
     * Generated from protobuf field <code>int64 code = 1;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     */
    protected $msg = '';
    /**
     * 商品是否参加满返活动 0默认; 1参加; 2不参加 (当不参加时 result字段无值,无意义)
     *
     * Generated from protobuf field <code>int64 joined = 3;</code>
     */
    protected $joined = 0;
    /**
     * Generated from protobuf field <code>.order.GetFullReturnRewardFromOrderItemIdResult result = 4;</code>
     */
    protected $result = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $code
     *           200代表成功; 非200代表失败
     *     @type string $msg
     *     @type int|string $joined
     *           商品是否参加满返活动 0默认; 1参加; 2不参加 (当不参加时 result字段无值,无意义)
     *     @type \app\components\proto\order\GetFullReturnRewardFromOrderItemIdResult $result
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Order\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * 200代表成功; 非200代表失败
     *
     * Generated from protobuf field <code>int64 code = 1;</code>
     * @return int|string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * 200代表成功; 非200代表失败
     *
     * Generated from protobuf field <code>int64 code = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt64($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

    /**
     * 商品是否参加满返活动 0默认; 1参加; 2不参加 (当不参加时 result字段无值,无意义)
     *
     * Generated from protobuf field <code>int64 joined = 3;</code>
     * @return int|string
     */
    public function getJoined()
    {
        return $this->joined;
    }

    /**
     * 商品是否参加满返活动 0默认; 1参加; 2不参加 (当不参加时 result字段无值,无意义)
     *
     * Generated from protobuf field <code>int64 joined = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setJoined($var)
    {
        GPBUtil::checkInt64($var);
        $this->joined = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.order.GetFullReturnRewardFromOrderItemIdResult result = 4;</code>
     * @return \app\components\proto\order\GetFullReturnRewardFromOrderItemIdResult|null
     */
    public function getResult()
    {
        return isset($this->result) ? $this->result : null;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>.order.GetFullReturnRewardFromOrderItemIdResult result = 4;</code>
     * @param \app\components\proto\order\GetFullReturnRewardFromOrderItemIdResult $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \app\components\proto\order\GetFullReturnRewardFromOrderItemIdResult::class);
        $this->result = $var;

        return $this;
    }

}

