<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/order/order.proto

namespace app\components\proto\order;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>order.MisFullReturnConfItem</code>
 */
class MisFullReturnConfItem extends \Google\Protobuf\Internal\Message
{
    /**
     * 满返组id,也作为map的key
     *
     * Generated from protobuf field <code>int64 group_id = 1;</code>
     */
    protected $group_id = 0;
    /**
     * 满返类型
     *
     * Generated from protobuf field <code>.order.FullReturnType type = 2;</code>
     */
    protected $type = 0;
    /**
     * 满返配置(每满返只有一条记录,阶梯满返配置 按照门槛从低到高排序)
     *
     * Generated from protobuf field <code>repeated .order.FullReturnConfTypeDetail conf_detail = 3;</code>
     */
    private $conf_detail;
    /**
     * 购物车文案
     *
     * Generated from protobuf field <code>string cart_tip = 4;</code>
     */
    protected $cart_tip = '';
    /**
     * 活动规则文案
     *
     * Generated from protobuf field <code>string rule_text = 5;</code>
     */
    protected $rule_text = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $group_id
     *           满返组id,也作为map的key
     *     @type int $type
     *           满返类型
     *     @type \app\components\proto\order\FullReturnConfTypeDetail[]|\Google\Protobuf\Internal\RepeatedField $conf_detail
     *           满返配置(每满返只有一条记录,阶梯满返配置 按照门槛从低到高排序)
     *     @type string $cart_tip
     *           购物车文案
     *     @type string $rule_text
     *           活动规则文案
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Order\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * 满返组id,也作为map的key
     *
     * Generated from protobuf field <code>int64 group_id = 1;</code>
     * @return int|string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * 满返组id,也作为map的key
     *
     * Generated from protobuf field <code>int64 group_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->group_id = $var;

        return $this;
    }

    /**
     * 满返类型
     *
     * Generated from protobuf field <code>.order.FullReturnType type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * 满返类型
     *
     * Generated from protobuf field <code>.order.FullReturnType type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \app\components\proto\order\FullReturnType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * 满返配置(每满返只有一条记录,阶梯满返配置 按照门槛从低到高排序)
     *
     * Generated from protobuf field <code>repeated .order.FullReturnConfTypeDetail conf_detail = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConfDetail()
    {
        return $this->conf_detail;
    }

    /**
     * 满返配置(每满返只有一条记录,阶梯满返配置 按照门槛从低到高排序)
     *
     * Generated from protobuf field <code>repeated .order.FullReturnConfTypeDetail conf_detail = 3;</code>
     * @param \app\components\proto\order\FullReturnConfTypeDetail[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConfDetail($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \app\components\proto\order\FullReturnConfTypeDetail::class);
        $this->conf_detail = $arr;

        return $this;
    }

    /**
     * 购物车文案
     *
     * Generated from protobuf field <code>string cart_tip = 4;</code>
     * @return string
     */
    public function getCartTip()
    {
        return $this->cart_tip;
    }

    /**
     * 购物车文案
     *
     * Generated from protobuf field <code>string cart_tip = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCartTip($var)
    {
        GPBUtil::checkString($var, True);
        $this->cart_tip = $var;

        return $this;
    }

    /**
     * 活动规则文案
     *
     * Generated from protobuf field <code>string rule_text = 5;</code>
     * @return string
     */
    public function getRuleText()
    {
        return $this->rule_text;
    }

    /**
     * 活动规则文案
     *
     * Generated from protobuf field <code>string rule_text = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRuleText($var)
    {
        GPBUtil::checkString($var, True);
        $this->rule_text = $var;

        return $this;
    }

}

