<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/order/order.proto

namespace app\components\proto\order;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MqNoticeRequest 消息回调参数
 *
 * Generated from protobuf message <code>order.MqNoticeRequest</code>
 */
class MqNoticeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 消息json格式
     *
     * Generated from protobuf field <code>string msg_json = 1;</code>
     */
    protected $msg_json = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $msg_json
     *           消息json格式
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Order\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * 消息json格式
     *
     * Generated from protobuf field <code>string msg_json = 1;</code>
     * @return string
     */
    public function getMsgJson()
    {
        return $this->msg_json;
    }

    /**
     * 消息json格式
     *
     * Generated from protobuf field <code>string msg_json = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgJson($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg_json = $var;

        return $this;
    }

}

