<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/order/order.proto

namespace app\components\proto\order;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SvoucherExpireTimeRequest 获取佣金劵过期时间-请求参数
 *
 * Generated from protobuf message <code>order.SvoucherExpireTimeRequest</code>
 */
class SvoucherExpireTimeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 用户优惠券ID
     *
     * Generated from protobuf field <code>repeated int64 user_voucher_ids = 1;</code>
     */
    private $user_voucher_ids;
    /**
     * 缓存时间，默认不缓存(非必传)
     *
     * Generated from protobuf field <code>int64 cache_time = 2;</code>
     */
    protected $cache_time = 0;
    /**
     * 业务模块：www、mis、zzapi(非必传)
     *
     * Generated from protobuf field <code>string business_module = 3;</code>
     */
    protected $business_module = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $user_voucher_ids
     *           用户优惠券ID
     *     @type int|string $cache_time
     *           缓存时间，默认不缓存(非必传)
     *     @type string $business_module
     *           业务模块：www、mis、zzapi(非必传)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Order\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * 用户优惠券ID
     *
     * Generated from protobuf field <code>repeated int64 user_voucher_ids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserVoucherIds()
    {
        return $this->user_voucher_ids;
    }

    /**
     * 用户优惠券ID
     *
     * Generated from protobuf field <code>repeated int64 user_voucher_ids = 1;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserVoucherIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->user_voucher_ids = $arr;

        return $this;
    }

    /**
     * 缓存时间，默认不缓存(非必传)
     *
     * Generated from protobuf field <code>int64 cache_time = 2;</code>
     * @return int|string
     */
    public function getCacheTime()
    {
        return $this->cache_time;
    }

    /**
     * 缓存时间，默认不缓存(非必传)
     *
     * Generated from protobuf field <code>int64 cache_time = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCacheTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->cache_time = $var;

        return $this;
    }

    /**
     * 业务模块：www、mis、zzapi(非必传)
     *
     * Generated from protobuf field <code>string business_module = 3;</code>
     * @return string
     */
    public function getBusinessModule()
    {
        return $this->business_module;
    }

    /**
     * 业务模块：www、mis、zzapi(非必传)
     *
     * Generated from protobuf field <code>string business_module = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBusinessModule($var)
    {
        GPBUtil::checkString($var, True);
        $this->business_module = $var;

        return $this;
    }

}

