<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param.proto

namespace app\components\proto\voucher;

if (false) {
    /**
     * This class is deprecated. Use app\components\proto\voucher\BatchUpdateDrawCountRequest\voucher_info instead.
     * @deprecated
     */
    class BatchUpdateDrawCountRequest_voucher_info {}
}
class_exists(BatchUpdateDrawCountRequest\voucher_info::class);
@trigger_error('app\components\proto\voucher\BatchUpdateDrawCountRequest_voucher_info is deprecated and will be removed in the next major release. Use app\components\proto\voucher\BatchUpdateDrawCountRequest\voucher_info instead', E_USER_DEPRECATED);

