<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *批量发送优惠券-返回
 *
 * Generated from protobuf message <code>voucher_types.BatchSendVoucherResponse</code>
 */
class BatchSendVoucherResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 code = 1;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     */
    protected $msg = '';
    /**
     * Generated from protobuf field <code>repeated .voucher_types.BatchSendVoucherResponseItem user_result = 3;</code>
     */
    private $user_result;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $code
     *     @type string $msg
     *     @type \app\components\proto\voucher\BatchSendVoucherResponseItem[]|\Google\Protobuf\Internal\RepeatedField $user_result
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParam::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 code = 1;</code>
     * @return int|string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int64 code = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt64($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .voucher_types.BatchSendVoucherResponseItem user_result = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserResult()
    {
        return $this->user_result;
    }

    /**
     * Generated from protobuf field <code>repeated .voucher_types.BatchSendVoucherResponseItem user_result = 3;</code>
     * @param \app\components\proto\voucher\BatchSendVoucherResponseItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserResult($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \app\components\proto\voucher\BatchSendVoucherResponseItem::class);
        $this->user_result = $arr;

        return $this;
    }

}

