<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param-read.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>voucher_types_read.CheckCalPriceVoucherListByTimePointRequest</code>
 */
class CheckCalPriceVoucherListByTimePointRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 time_point = 1;</code>
     */
    protected $time_point = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $time_point
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParamRead::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 time_point = 1;</code>
     * @return int|string
     */
    public function getTimePoint()
    {
        return $this->time_point;
    }

    /**
     * Generated from protobuf field <code>int64 time_point = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimePoint($var)
    {
        GPBUtil::checkInt64($var);
        $this->time_point = $var;

        return $this;
    }

}

