<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param-read.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>voucher_types_read.GetCountUserVoucherGroupByVIdResponseItem</code>
 */
class GetCountUserVoucherGroupByVIdResponseItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 C = 1;</code>
     */
    protected $C = 0;
    /**
     * Generated from protobuf field <code>int64 voucher_id = 2;</code>
     */
    protected $voucher_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $C
     *     @type int|string $voucher_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParamRead::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 C = 1;</code>
     * @return int|string
     */
    public function getC()
    {
        return $this->C;
    }

    /**
     * Generated from protobuf field <code>int64 C = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setC($var)
    {
        GPBUtil::checkInt64($var);
        $this->C = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 voucher_id = 2;</code>
     * @return int|string
     */
    public function getVoucherId()
    {
        return $this->voucher_id;
    }

    /**
     * Generated from protobuf field <code>int64 voucher_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVoucherId($var)
    {
        GPBUtil::checkInt64($var);
        $this->voucher_id = $var;

        return $this;
    }

}

