<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param-read.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>voucher_types_read.GetHasVoucherUserByVidAndUidRequest</code>
 */
class GetHasVoucherUserByVidAndUidRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>repeated int64 voucher_id = 1;</code>
     */
    private $voucher_id;
    /**
     * 用户ID
     *
     * Generated from protobuf field <code>repeated int64 user_id = 2;</code>
     */
    private $user_id;
    /**
     * 创建时间大于
     *
     * Generated from protobuf field <code>int64 ctime_gt = 3;</code>
     */
    protected $ctime_gt = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $voucher_id
     *           优惠券ID
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $user_id
     *           用户ID
     *     @type int|string $ctime_gt
     *           创建时间大于
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParamRead::initOnce();
        parent::__construct($data);
    }

    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>repeated int64 voucher_id = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVoucherId()
    {
        return $this->voucher_id;
    }

    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>repeated int64 voucher_id = 1;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVoucherId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->voucher_id = $arr;

        return $this;
    }

    /**
     * 用户ID
     *
     * Generated from protobuf field <code>repeated int64 user_id = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * 用户ID
     *
     * Generated from protobuf field <code>repeated int64 user_id = 2;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->user_id = $arr;

        return $this;
    }

    /**
     * 创建时间大于
     *
     * Generated from protobuf field <code>int64 ctime_gt = 3;</code>
     * @return int|string
     */
    public function getCtimeGt()
    {
        return $this->ctime_gt;
    }

    /**
     * 创建时间大于
     *
     * Generated from protobuf field <code>int64 ctime_gt = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtimeGt($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctime_gt = $var;

        return $this;
    }

}

