<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param-read.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 卖家中心 - 获取商户优惠券
 *
 * Generated from protobuf message <code>voucher_types_read.GetMerVoucherRequest</code>
 */
class GetMerVoucherRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 商户ID
     *
     * Generated from protobuf field <code>int32 seller_id = 1;</code>
     */
    protected $seller_id = 0;
    /**
     * 用户ID
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     */
    protected $user_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $seller_id
     *           商户ID
     *     @type int|string $user_id
     *           用户ID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParamRead::initOnce();
        parent::__construct($data);
    }

    /**
     * 商户ID
     *
     * Generated from protobuf field <code>int32 seller_id = 1;</code>
     * @return int
     */
    public function getSellerId()
    {
        return $this->seller_id;
    }

    /**
     * 商户ID
     *
     * Generated from protobuf field <code>int32 seller_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSellerId($var)
    {
        GPBUtil::checkInt32($var);
        $this->seller_id = $var;

        return $this;
    }

    /**
     * 用户ID
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * 用户ID
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

}

