<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param-read.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>voucher_types_read.GetPlumVouchersRequest</code>
 */
class GetPlumVouchersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string seller_id = 1;</code>
     */
    protected $seller_id = '';
    /**
     * Generated from protobuf field <code>bool is_out_living = 2;</code>
     */
    protected $is_out_living = false;
    /**
     * Generated from protobuf field <code>bool is_new_user = 3;</code>
     */
    protected $is_new_user = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $seller_id
     *     @type bool $is_out_living
     *     @type bool $is_new_user
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParamRead::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string seller_id = 1;</code>
     * @return string
     */
    public function getSellerId()
    {
        return $this->seller_id;
    }

    /**
     * Generated from protobuf field <code>string seller_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSellerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->seller_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_out_living = 2;</code>
     * @return bool
     */
    public function getIsOutLiving()
    {
        return $this->is_out_living;
    }

    /**
     * Generated from protobuf field <code>bool is_out_living = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsOutLiving($var)
    {
        GPBUtil::checkBool($var);
        $this->is_out_living = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_new_user = 3;</code>
     * @return bool
     */
    public function getIsNewUser()
    {
        return $this->is_new_user;
    }

    /**
     * Generated from protobuf field <code>bool is_new_user = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsNewUser($var)
    {
        GPBUtil::checkBool($var);
        $this->is_new_user = $var;

        return $this;
    }

}

