<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param-read.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>voucher_types_read.GetTimeSlotUserSumDataResponseData</code>
 */
class GetTimeSlotUserSumDataResponseData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string m_yhqzs = 1;</code>
     */
    protected $m_yhqzs = '';
    /**
     * Generated from protobuf field <code>string m_yhqhds = 2;</code>
     */
    protected $m_yhqhds = '';
    /**
     * Generated from protobuf field <code>string m_yhqje = 3;</code>
     */
    protected $m_yhqje = '';
    /**
     * Generated from protobuf field <code>string m_syyhqzs = 4;</code>
     */
    protected $m_syyhqzs = '';
    /**
     * Generated from protobuf field <code>string m_syyhqhds = 5;</code>
     */
    protected $m_syyhqhds = '';
    /**
     * Generated from protobuf field <code>string m_syyhqje = 6;</code>
     */
    protected $m_syyhqje = '';
    /**
     * Generated from protobuf field <code>string m_qtndqyhqzs = 7;</code>
     */
    protected $m_qtndqyhqzs = '';
    /**
     * Generated from protobuf field <code>string m_qtndqyhqje = 8;</code>
     */
    protected $m_qtndqyhqje = '';
    /**
     * Generated from protobuf field <code>string m_swtndqyhqzs = 9;</code>
     */
    protected $m_swtndqyhqzs = '';
    /**
     * Generated from protobuf field <code>string m_swtndqyhqje = 10;</code>
     */
    protected $m_swtndqyhqje = '';
    /**
     * Generated from protobuf field <code>string m_sstndqyhqzs = 11;</code>
     */
    protected $m_sstndqyhqzs = '';
    /**
     * Generated from protobuf field <code>string m_sstndqyhqje = 12;</code>
     */
    protected $m_sstndqyhqje = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $m_yhqzs
     *     @type string $m_yhqhds
     *     @type string $m_yhqje
     *     @type string $m_syyhqzs
     *     @type string $m_syyhqhds
     *     @type string $m_syyhqje
     *     @type string $m_qtndqyhqzs
     *     @type string $m_qtndqyhqje
     *     @type string $m_swtndqyhqzs
     *     @type string $m_swtndqyhqje
     *     @type string $m_sstndqyhqzs
     *     @type string $m_sstndqyhqje
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParamRead::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string m_yhqzs = 1;</code>
     * @return string
     */
    public function getMYhqzs()
    {
        return $this->m_yhqzs;
    }

    /**
     * Generated from protobuf field <code>string m_yhqzs = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMYhqzs($var)
    {
        GPBUtil::checkString($var, True);
        $this->m_yhqzs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string m_yhqhds = 2;</code>
     * @return string
     */
    public function getMYhqhds()
    {
        return $this->m_yhqhds;
    }

    /**
     * Generated from protobuf field <code>string m_yhqhds = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMYhqhds($var)
    {
        GPBUtil::checkString($var, True);
        $this->m_yhqhds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string m_yhqje = 3;</code>
     * @return string
     */
    public function getMYhqje()
    {
        return $this->m_yhqje;
    }

    /**
     * Generated from protobuf field <code>string m_yhqje = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMYhqje($var)
    {
        GPBUtil::checkString($var, True);
        $this->m_yhqje = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string m_syyhqzs = 4;</code>
     * @return string
     */
    public function getMSyyhqzs()
    {
        return $this->m_syyhqzs;
    }

    /**
     * Generated from protobuf field <code>string m_syyhqzs = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMSyyhqzs($var)
    {
        GPBUtil::checkString($var, True);
        $this->m_syyhqzs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string m_syyhqhds = 5;</code>
     * @return string
     */
    public function getMSyyhqhds()
    {
        return $this->m_syyhqhds;
    }

    /**
     * Generated from protobuf field <code>string m_syyhqhds = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMSyyhqhds($var)
    {
        GPBUtil::checkString($var, True);
        $this->m_syyhqhds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string m_syyhqje = 6;</code>
     * @return string
     */
    public function getMSyyhqje()
    {
        return $this->m_syyhqje;
    }

    /**
     * Generated from protobuf field <code>string m_syyhqje = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMSyyhqje($var)
    {
        GPBUtil::checkString($var, True);
        $this->m_syyhqje = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string m_qtndqyhqzs = 7;</code>
     * @return string
     */
    public function getMQtndqyhqzs()
    {
        return $this->m_qtndqyhqzs;
    }

    /**
     * Generated from protobuf field <code>string m_qtndqyhqzs = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setMQtndqyhqzs($var)
    {
        GPBUtil::checkString($var, True);
        $this->m_qtndqyhqzs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string m_qtndqyhqje = 8;</code>
     * @return string
     */
    public function getMQtndqyhqje()
    {
        return $this->m_qtndqyhqje;
    }

    /**
     * Generated from protobuf field <code>string m_qtndqyhqje = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMQtndqyhqje($var)
    {
        GPBUtil::checkString($var, True);
        $this->m_qtndqyhqje = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string m_swtndqyhqzs = 9;</code>
     * @return string
     */
    public function getMSwtndqyhqzs()
    {
        return $this->m_swtndqyhqzs;
    }

    /**
     * Generated from protobuf field <code>string m_swtndqyhqzs = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setMSwtndqyhqzs($var)
    {
        GPBUtil::checkString($var, True);
        $this->m_swtndqyhqzs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string m_swtndqyhqje = 10;</code>
     * @return string
     */
    public function getMSwtndqyhqje()
    {
        return $this->m_swtndqyhqje;
    }

    /**
     * Generated from protobuf field <code>string m_swtndqyhqje = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setMSwtndqyhqje($var)
    {
        GPBUtil::checkString($var, True);
        $this->m_swtndqyhqje = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string m_sstndqyhqzs = 11;</code>
     * @return string
     */
    public function getMSstndqyhqzs()
    {
        return $this->m_sstndqyhqzs;
    }

    /**
     * Generated from protobuf field <code>string m_sstndqyhqzs = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setMSstndqyhqzs($var)
    {
        GPBUtil::checkString($var, True);
        $this->m_sstndqyhqzs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string m_sstndqyhqje = 12;</code>
     * @return string
     */
    public function getMSstndqyhqje()
    {
        return $this->m_sstndqyhqje;
    }

    /**
     * Generated from protobuf field <code>string m_sstndqyhqje = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setMSstndqyhqje($var)
    {
        GPBUtil::checkString($var, True);
        $this->m_sstndqyhqje = $var;

        return $this;
    }

}

