<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param-read.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>voucher_types_read.GetUserSumBenefitValueData</code>
 */
class GetUserSumBenefitValueData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>float benefit_value = 2;</code>
     */
    protected $benefit_value = 0.0;
    /**
     * Generated from protobuf field <code>int64 user_voucher_id = 3;</code>
     */
    protected $user_voucher_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_id
     *     @type float $benefit_value
     *     @type int|string $user_voucher_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParamRead::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float benefit_value = 2;</code>
     * @return float
     */
    public function getBenefitValue()
    {
        return $this->benefit_value;
    }

    /**
     * Generated from protobuf field <code>float benefit_value = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setBenefitValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->benefit_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 user_voucher_id = 3;</code>
     * @return int|string
     */
    public function getUserVoucherId()
    {
        return $this->user_voucher_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_voucher_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserVoucherId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_voucher_id = $var;

        return $this;
    }

}

