<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param-read.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>voucher_types_read.GetVoucherBySettingsData</code>
 */
class GetVoucherBySettingsData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 voucher_id = 1;</code>
     */
    protected $voucher_id = 0;
    /**
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>string scope_items_text = 3;</code>
     */
    protected $scope_items_text = '';
    /**
     * Generated from protobuf field <code>float benefit_value = 4;</code>
     */
    protected $benefit_value = 0.0;
    /**
     * Generated from protobuf field <code>float max_off_price = 5;</code>
     */
    protected $max_off_price = 0.0;
    /**
     * Generated from protobuf field <code>string user_type = 6;</code>
     */
    protected $user_type = '';
    /**
     * Generated from protobuf field <code>string voucher_cate = 7;</code>
     */
    protected $voucher_cate = '';
    /**
     * Generated from protobuf field <code>string category_list = 8;</code>
     */
    protected $category_list = '';
    /**
     * Generated from protobuf field <code>string brand_list = 9;</code>
     */
    protected $brand_list = '';
    /**
     * Generated from protobuf field <code>string effect_users = 10;</code>
     */
    protected $effect_users = '';
    /**
     * Generated from protobuf field <code>int64 count_limited_per_user = 11;</code>
     */
    protected $count_limited_per_user = 0;
    /**
     * Generated from protobuf field <code>string grant_frequency = 12;</code>
     */
    protected $grant_frequency = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $voucher_id
     *     @type string $code
     *     @type string $scope_items_text
     *     @type float $benefit_value
     *     @type float $max_off_price
     *     @type string $user_type
     *     @type string $voucher_cate
     *     @type string $category_list
     *     @type string $brand_list
     *     @type string $effect_users
     *     @type int|string $count_limited_per_user
     *     @type string $grant_frequency
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParamRead::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 voucher_id = 1;</code>
     * @return int|string
     */
    public function getVoucherId()
    {
        return $this->voucher_id;
    }

    /**
     * Generated from protobuf field <code>int64 voucher_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVoucherId($var)
    {
        GPBUtil::checkInt64($var);
        $this->voucher_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string scope_items_text = 3;</code>
     * @return string
     */
    public function getScopeItemsText()
    {
        return $this->scope_items_text;
    }

    /**
     * Generated from protobuf field <code>string scope_items_text = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setScopeItemsText($var)
    {
        GPBUtil::checkString($var, True);
        $this->scope_items_text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float benefit_value = 4;</code>
     * @return float
     */
    public function getBenefitValue()
    {
        return $this->benefit_value;
    }

    /**
     * Generated from protobuf field <code>float benefit_value = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setBenefitValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->benefit_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float max_off_price = 5;</code>
     * @return float
     */
    public function getMaxOffPrice()
    {
        return $this->max_off_price;
    }

    /**
     * Generated from protobuf field <code>float max_off_price = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxOffPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->max_off_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_type = 6;</code>
     * @return string
     */
    public function getUserType()
    {
        return $this->user_type;
    }

    /**
     * Generated from protobuf field <code>string user_type = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUserType($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string voucher_cate = 7;</code>
     * @return string
     */
    public function getVoucherCate()
    {
        return $this->voucher_cate;
    }

    /**
     * Generated from protobuf field <code>string voucher_cate = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setVoucherCate($var)
    {
        GPBUtil::checkString($var, True);
        $this->voucher_cate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category_list = 8;</code>
     * @return string
     */
    public function getCategoryList()
    {
        return $this->category_list;
    }

    /**
     * Generated from protobuf field <code>string category_list = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryList($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_list = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string brand_list = 9;</code>
     * @return string
     */
    public function getBrandList()
    {
        return $this->brand_list;
    }

    /**
     * Generated from protobuf field <code>string brand_list = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setBrandList($var)
    {
        GPBUtil::checkString($var, True);
        $this->brand_list = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string effect_users = 10;</code>
     * @return string
     */
    public function getEffectUsers()
    {
        return $this->effect_users;
    }

    /**
     * Generated from protobuf field <code>string effect_users = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setEffectUsers($var)
    {
        GPBUtil::checkString($var, True);
        $this->effect_users = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 count_limited_per_user = 11;</code>
     * @return int|string
     */
    public function getCountLimitedPerUser()
    {
        return $this->count_limited_per_user;
    }

    /**
     * Generated from protobuf field <code>int64 count_limited_per_user = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCountLimitedPerUser($var)
    {
        GPBUtil::checkInt64($var);
        $this->count_limited_per_user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string grant_frequency = 12;</code>
     * @return string
     */
    public function getGrantFrequency()
    {
        return $this->grant_frequency;
    }

    /**
     * Generated from protobuf field <code>string grant_frequency = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setGrantFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->grant_frequency = $var;

        return $this;
    }

}

