<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param-read.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>voucher_types_read.GetVoucherRequest</code>
 */
class GetVoucherRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 券ID
     *
     * Generated from protobuf field <code>repeated int64 voucher_id = 1;</code>
     */
    private $voucher_id;
    /**
     * 券组ID
     *
     * Generated from protobuf field <code>repeated int64 voucher_group_id = 2;</code>
     */
    private $voucher_group_id;
    /**
     * code
     *
     * Generated from protobuf field <code>repeated string code = 3;</code>
     */
    private $code;
    /**
     * 可领取人群 不传代表全部
     *
     * Generated from protobuf field <code>string effect_users = 4;</code>
     */
    protected $effect_users = '';
    /**
     * 优惠券类型 不传代表全部
     *
     * Generated from protobuf field <code>string user_type = 5;</code>
     */
    protected $user_type = '';
    /**
     * 是否生效 0全部 1是 2否
     *
     * Generated from protobuf field <code>int64 enabled = 6;</code>
     */
    protected $enabled = 0;
    /**
     * 查询类型 data数据 count数量 all全部 默认data
     *
     * Generated from protobuf field <code>string find_type = 7;</code>
     */
    protected $find_type = '';
    /**
     * 排序 ["id:0"](0正序，1倒序)
     *
     * Generated from protobuf field <code>repeated string order_by = 8;</code>
     */
    private $order_by;
    /**
     * 查询字段
     *
     * Generated from protobuf field <code>repeated string fields = 9;</code>
     */
    private $fields;
    /**
     * 页码 默认1
     *
     * Generated from protobuf field <code>int64 page = 10;</code>
     */
    protected $page = 0;
    /**
     * 页大小 默认10
     *
     * Generated from protobuf field <code>int64 size = 11;</code>
     */
    protected $size = 0;
    /**
     * 是否分页
     *
     * Generated from protobuf field <code>bool is_paginate = 12;</code>
     */
    protected $is_paginate = false;
    /**
     * 用户是否可以主动领取 1是 2否
     *
     * Generated from protobuf field <code>int64 must_grant = 13;</code>
     */
    protected $must_grant = 0;
    /**
     * 购买最小价格
     *
     * Generated from protobuf field <code>float min_price = 14;</code>
     */
    protected $min_price = 0.0;
    /**
     * 购买最大价格
     *
     * Generated from protobuf field <code>float max_price = 15;</code>
     */
    protected $max_price = 0.0;
    /**
     * 可领取开始时间
     *
     * Generated from protobuf field <code>int64 start_getable_time = 16;</code>
     */
    protected $start_getable_time = 0;
    /**
     * 可领取结束时间
     *
     * Generated from protobuf field <code>int64 end_getable_time = 17;</code>
     */
    protected $end_getable_time = 0;
    /**
     * getable_time <= ?
     *
     * Generated from protobuf field <code>string getable_time_le = 18;</code>
     */
    protected $getable_time_le = '';
    /**
     * price
     *
     * Generated from protobuf field <code>string eq_price = 19;</code>
     */
    protected $eq_price = '';
    /**
     * 限制优惠券存在库存 true:total_count > draw_count
     *
     * Generated from protobuf field <code>bool is_available_voucher = 20;</code>
     */
    protected $is_available_voucher = false;
    /**
     * group_by
     *
     * Generated from protobuf field <code>string group_by = 21;</code>
     */
    protected $group_by = '';
    /**
     * show_pos 2=0
     *
     * Generated from protobuf field <code>int64 show_pos = 22;</code>
     */
    protected $show_pos = 0;
    /**
     * start_time < ?
     *
     * Generated from protobuf field <code>int64 start_time_lt = 23;</code>
     */
    protected $start_time_lt = 0;
    /**
     * vc_id = ?
     *
     * Generated from protobuf field <code>int64 vc_id = 24;</code>
     */
    protected $vc_id = 0;
    /**
     * total_count >= ?
     *
     * Generated from protobuf field <code>bool is_total_count_ge_zero = 25;</code>
     */
    protected $is_total_count_ge_zero = false;
    /**
     * code_like
     *
     * Generated from protobuf field <code>string code_like = 26;</code>
     */
    protected $code_like = '';
    /**
     * end_time >= ?
     *
     * Generated from protobuf field <code>string end_time_ge = 27;</code>
     */
    protected $end_time_ge = '';
    /**
     * price > 0
     *
     * Generated from protobuf field <code>bool price_gt_zero = 28;</code>
     */
    protected $price_gt_zero = false;
    /**
     * can_use_days=value-1    =0时忽略该条件
     *
     * Generated from protobuf field <code>int64 can_use_days = 29;</code>
     */
    protected $can_use_days = 0;
    /**
     * 针对 end_time>? or end_time=0 的情况
     *
     * Generated from protobuf field <code>int64 end_time_zero = 30;</code>
     */
    protected $end_time_zero = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $voucher_id
     *           券ID
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $voucher_group_id
     *           券组ID
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $code
     *           code
     *     @type string $effect_users
     *           可领取人群 不传代表全部
     *     @type string $user_type
     *           优惠券类型 不传代表全部
     *     @type int|string $enabled
     *           是否生效 0全部 1是 2否
     *     @type string $find_type
     *           查询类型 data数据 count数量 all全部 默认data
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $order_by
     *           排序 ["id:0"](0正序，1倒序)
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $fields
     *           查询字段
     *     @type int|string $page
     *           页码 默认1
     *     @type int|string $size
     *           页大小 默认10
     *     @type bool $is_paginate
     *           是否分页
     *     @type int|string $must_grant
     *           用户是否可以主动领取 1是 2否
     *     @type float $min_price
     *           购买最小价格
     *     @type float $max_price
     *           购买最大价格
     *     @type int|string $start_getable_time
     *           可领取开始时间
     *     @type int|string $end_getable_time
     *           可领取结束时间
     *     @type string $getable_time_le
     *           getable_time <= ?
     *     @type string $eq_price
     *           price
     *     @type bool $is_available_voucher
     *           限制优惠券存在库存 true:total_count > draw_count
     *     @type string $group_by
     *           group_by
     *     @type int|string $show_pos
     *           show_pos 2=0
     *     @type int|string $start_time_lt
     *           start_time < ?
     *     @type int|string $vc_id
     *           vc_id = ?
     *     @type bool $is_total_count_ge_zero
     *           total_count >= ?
     *     @type string $code_like
     *           code_like
     *     @type string $end_time_ge
     *           end_time >= ?
     *     @type bool $price_gt_zero
     *           price > 0
     *     @type int|string $can_use_days
     *           can_use_days=value-1    =0时忽略该条件
     *     @type int|string $end_time_zero
     *           针对 end_time>? or end_time=0 的情况
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParamRead::initOnce();
        parent::__construct($data);
    }

    /**
     * 券ID
     *
     * Generated from protobuf field <code>repeated int64 voucher_id = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVoucherId()
    {
        return $this->voucher_id;
    }

    /**
     * 券ID
     *
     * Generated from protobuf field <code>repeated int64 voucher_id = 1;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVoucherId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->voucher_id = $arr;

        return $this;
    }

    /**
     * 券组ID
     *
     * Generated from protobuf field <code>repeated int64 voucher_group_id = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVoucherGroupId()
    {
        return $this->voucher_group_id;
    }

    /**
     * 券组ID
     *
     * Generated from protobuf field <code>repeated int64 voucher_group_id = 2;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVoucherGroupId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->voucher_group_id = $arr;

        return $this;
    }

    /**
     * code
     *
     * Generated from protobuf field <code>repeated string code = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * code
     *
     * Generated from protobuf field <code>repeated string code = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCode($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->code = $arr;

        return $this;
    }

    /**
     * 可领取人群 不传代表全部
     *
     * Generated from protobuf field <code>string effect_users = 4;</code>
     * @return string
     */
    public function getEffectUsers()
    {
        return $this->effect_users;
    }

    /**
     * 可领取人群 不传代表全部
     *
     * Generated from protobuf field <code>string effect_users = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEffectUsers($var)
    {
        GPBUtil::checkString($var, True);
        $this->effect_users = $var;

        return $this;
    }

    /**
     * 优惠券类型 不传代表全部
     *
     * Generated from protobuf field <code>string user_type = 5;</code>
     * @return string
     */
    public function getUserType()
    {
        return $this->user_type;
    }

    /**
     * 优惠券类型 不传代表全部
     *
     * Generated from protobuf field <code>string user_type = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUserType($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_type = $var;

        return $this;
    }

    /**
     * 是否生效 0全部 1是 2否
     *
     * Generated from protobuf field <code>int64 enabled = 6;</code>
     * @return int|string
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * 是否生效 0全部 1是 2否
     *
     * Generated from protobuf field <code>int64 enabled = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkInt64($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * 查询类型 data数据 count数量 all全部 默认data
     *
     * Generated from protobuf field <code>string find_type = 7;</code>
     * @return string
     */
    public function getFindType()
    {
        return $this->find_type;
    }

    /**
     * 查询类型 data数据 count数量 all全部 默认data
     *
     * Generated from protobuf field <code>string find_type = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setFindType($var)
    {
        GPBUtil::checkString($var, True);
        $this->find_type = $var;

        return $this;
    }

    /**
     * 排序 ["id:0"](0正序，1倒序)
     *
     * Generated from protobuf field <code>repeated string order_by = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrderBy()
    {
        return $this->order_by;
    }

    /**
     * 排序 ["id:0"](0正序，1倒序)
     *
     * Generated from protobuf field <code>repeated string order_by = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrderBy($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->order_by = $arr;

        return $this;
    }

    /**
     * 查询字段
     *
     * Generated from protobuf field <code>repeated string fields = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * 查询字段
     *
     * Generated from protobuf field <code>repeated string fields = 9;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFields($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->fields = $arr;

        return $this;
    }

    /**
     * 页码 默认1
     *
     * Generated from protobuf field <code>int64 page = 10;</code>
     * @return int|string
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * 页码 默认1
     *
     * Generated from protobuf field <code>int64 page = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt64($var);
        $this->page = $var;

        return $this;
    }

    /**
     * 页大小 默认10
     *
     * Generated from protobuf field <code>int64 size = 11;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * 页大小 默认10
     *
     * Generated from protobuf field <code>int64 size = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->size = $var;

        return $this;
    }

    /**
     * 是否分页
     *
     * Generated from protobuf field <code>bool is_paginate = 12;</code>
     * @return bool
     */
    public function getIsPaginate()
    {
        return $this->is_paginate;
    }

    /**
     * 是否分页
     *
     * Generated from protobuf field <code>bool is_paginate = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsPaginate($var)
    {
        GPBUtil::checkBool($var);
        $this->is_paginate = $var;

        return $this;
    }

    /**
     * 用户是否可以主动领取 1是 2否
     *
     * Generated from protobuf field <code>int64 must_grant = 13;</code>
     * @return int|string
     */
    public function getMustGrant()
    {
        return $this->must_grant;
    }

    /**
     * 用户是否可以主动领取 1是 2否
     *
     * Generated from protobuf field <code>int64 must_grant = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMustGrant($var)
    {
        GPBUtil::checkInt64($var);
        $this->must_grant = $var;

        return $this;
    }

    /**
     * 购买最小价格
     *
     * Generated from protobuf field <code>float min_price = 14;</code>
     * @return float
     */
    public function getMinPrice()
    {
        return $this->min_price;
    }

    /**
     * 购买最小价格
     *
     * Generated from protobuf field <code>float min_price = 14;</code>
     * @param float $var
     * @return $this
     */
    public function setMinPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->min_price = $var;

        return $this;
    }

    /**
     * 购买最大价格
     *
     * Generated from protobuf field <code>float max_price = 15;</code>
     * @return float
     */
    public function getMaxPrice()
    {
        return $this->max_price;
    }

    /**
     * 购买最大价格
     *
     * Generated from protobuf field <code>float max_price = 15;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->max_price = $var;

        return $this;
    }

    /**
     * 可领取开始时间
     *
     * Generated from protobuf field <code>int64 start_getable_time = 16;</code>
     * @return int|string
     */
    public function getStartGetableTime()
    {
        return $this->start_getable_time;
    }

    /**
     * 可领取开始时间
     *
     * Generated from protobuf field <code>int64 start_getable_time = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartGetableTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_getable_time = $var;

        return $this;
    }

    /**
     * 可领取结束时间
     *
     * Generated from protobuf field <code>int64 end_getable_time = 17;</code>
     * @return int|string
     */
    public function getEndGetableTime()
    {
        return $this->end_getable_time;
    }

    /**
     * 可领取结束时间
     *
     * Generated from protobuf field <code>int64 end_getable_time = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndGetableTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->end_getable_time = $var;

        return $this;
    }

    /**
     * getable_time <= ?
     *
     * Generated from protobuf field <code>string getable_time_le = 18;</code>
     * @return string
     */
    public function getGetableTimeLe()
    {
        return $this->getable_time_le;
    }

    /**
     * getable_time <= ?
     *
     * Generated from protobuf field <code>string getable_time_le = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setGetableTimeLe($var)
    {
        GPBUtil::checkString($var, True);
        $this->getable_time_le = $var;

        return $this;
    }

    /**
     * price
     *
     * Generated from protobuf field <code>string eq_price = 19;</code>
     * @return string
     */
    public function getEqPrice()
    {
        return $this->eq_price;
    }

    /**
     * price
     *
     * Generated from protobuf field <code>string eq_price = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setEqPrice($var)
    {
        GPBUtil::checkString($var, True);
        $this->eq_price = $var;

        return $this;
    }

    /**
     * 限制优惠券存在库存 true:total_count > draw_count
     *
     * Generated from protobuf field <code>bool is_available_voucher = 20;</code>
     * @return bool
     */
    public function getIsAvailableVoucher()
    {
        return $this->is_available_voucher;
    }

    /**
     * 限制优惠券存在库存 true:total_count > draw_count
     *
     * Generated from protobuf field <code>bool is_available_voucher = 20;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAvailableVoucher($var)
    {
        GPBUtil::checkBool($var);
        $this->is_available_voucher = $var;

        return $this;
    }

    /**
     * group_by
     *
     * Generated from protobuf field <code>string group_by = 21;</code>
     * @return string
     */
    public function getGroupBy()
    {
        return $this->group_by;
    }

    /**
     * group_by
     *
     * Generated from protobuf field <code>string group_by = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_by = $var;

        return $this;
    }

    /**
     * show_pos 2=0
     *
     * Generated from protobuf field <code>int64 show_pos = 22;</code>
     * @return int|string
     */
    public function getShowPos()
    {
        return $this->show_pos;
    }

    /**
     * show_pos 2=0
     *
     * Generated from protobuf field <code>int64 show_pos = 22;</code>
     * @param int|string $var
     * @return $this
     */
    public function setShowPos($var)
    {
        GPBUtil::checkInt64($var);
        $this->show_pos = $var;

        return $this;
    }

    /**
     * start_time < ?
     *
     * Generated from protobuf field <code>int64 start_time_lt = 23;</code>
     * @return int|string
     */
    public function getStartTimeLt()
    {
        return $this->start_time_lt;
    }

    /**
     * start_time < ?
     *
     * Generated from protobuf field <code>int64 start_time_lt = 23;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTimeLt($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_time_lt = $var;

        return $this;
    }

    /**
     * vc_id = ?
     *
     * Generated from protobuf field <code>int64 vc_id = 24;</code>
     * @return int|string
     */
    public function getVcId()
    {
        return $this->vc_id;
    }

    /**
     * vc_id = ?
     *
     * Generated from protobuf field <code>int64 vc_id = 24;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVcId($var)
    {
        GPBUtil::checkInt64($var);
        $this->vc_id = $var;

        return $this;
    }

    /**
     * total_count >= ?
     *
     * Generated from protobuf field <code>bool is_total_count_ge_zero = 25;</code>
     * @return bool
     */
    public function getIsTotalCountGeZero()
    {
        return $this->is_total_count_ge_zero;
    }

    /**
     * total_count >= ?
     *
     * Generated from protobuf field <code>bool is_total_count_ge_zero = 25;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTotalCountGeZero($var)
    {
        GPBUtil::checkBool($var);
        $this->is_total_count_ge_zero = $var;

        return $this;
    }

    /**
     * code_like
     *
     * Generated from protobuf field <code>string code_like = 26;</code>
     * @return string
     */
    public function getCodeLike()
    {
        return $this->code_like;
    }

    /**
     * code_like
     *
     * Generated from protobuf field <code>string code_like = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setCodeLike($var)
    {
        GPBUtil::checkString($var, True);
        $this->code_like = $var;

        return $this;
    }

    /**
     * end_time >= ?
     *
     * Generated from protobuf field <code>string end_time_ge = 27;</code>
     * @return string
     */
    public function getEndTimeGe()
    {
        return $this->end_time_ge;
    }

    /**
     * end_time >= ?
     *
     * Generated from protobuf field <code>string end_time_ge = 27;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTimeGe($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_time_ge = $var;

        return $this;
    }

    /**
     * price > 0
     *
     * Generated from protobuf field <code>bool price_gt_zero = 28;</code>
     * @return bool
     */
    public function getPriceGtZero()
    {
        return $this->price_gt_zero;
    }

    /**
     * price > 0
     *
     * Generated from protobuf field <code>bool price_gt_zero = 28;</code>
     * @param bool $var
     * @return $this
     */
    public function setPriceGtZero($var)
    {
        GPBUtil::checkBool($var);
        $this->price_gt_zero = $var;

        return $this;
    }

    /**
     * can_use_days=value-1    =0时忽略该条件
     *
     * Generated from protobuf field <code>int64 can_use_days = 29;</code>
     * @return int|string
     */
    public function getCanUseDays()
    {
        return $this->can_use_days;
    }

    /**
     * can_use_days=value-1    =0时忽略该条件
     *
     * Generated from protobuf field <code>int64 can_use_days = 29;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCanUseDays($var)
    {
        GPBUtil::checkInt64($var);
        $this->can_use_days = $var;

        return $this;
    }

    /**
     * 针对 end_time>? or end_time=0 的情况
     *
     * Generated from protobuf field <code>int64 end_time_zero = 30;</code>
     * @return int|string
     */
    public function getEndTimeZero()
    {
        return $this->end_time_zero;
    }

    /**
     * 针对 end_time>? or end_time=0 的情况
     *
     * Generated from protobuf field <code>int64 end_time_zero = 30;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTimeZero($var)
    {
        GPBUtil::checkInt64($var);
        $this->end_time_zero = $var;

        return $this;
    }

}

