<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>voucher_types.MergeUserVoucherRequest</code>
 */
class MergeUserVoucherRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *原user_id
     *
     * Generated from protobuf field <code>int64 source_user_id = 1;</code>
     */
    protected $source_user_id = 0;
    /**
     *目标user_id
     *
     * Generated from protobuf field <code>int64 target_user_id = 2;</code>
     */
    protected $target_user_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $source_user_id
     *          原user_id
     *     @type int|string $target_user_id
     *          目标user_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParam::initOnce();
        parent::__construct($data);
    }

    /**
     *原user_id
     *
     * Generated from protobuf field <code>int64 source_user_id = 1;</code>
     * @return int|string
     */
    public function getSourceUserId()
    {
        return $this->source_user_id;
    }

    /**
     *原user_id
     *
     * Generated from protobuf field <code>int64 source_user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSourceUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->source_user_id = $var;

        return $this;
    }

    /**
     *目标user_id
     *
     * Generated from protobuf field <code>int64 target_user_id = 2;</code>
     * @return int|string
     */
    public function getTargetUserId()
    {
        return $this->target_user_id;
    }

    /**
     *目标user_id
     *
     * Generated from protobuf field <code>int64 target_user_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTargetUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->target_user_id = $var;

        return $this;
    }

}

