<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>voucher_types.SaveVoucherGroupItem</code>
 */
class SaveVoucherGroupItem extends \Google\Protobuf\Internal\Message
{
    /**
     *优惠券组id [选填 有代表更新]
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     *组code
     *
     * Generated from protobuf field <code>string code = 2;</code>
     */
    protected $code = '';
    /**
     *组名字
     *
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     *组类型: 优惠券类型，system:系统优惠券，由系统发放给用户；activity：特定活动时给用户
     *
     * Generated from protobuf field <code>string group_type = 4;</code>
     */
    protected $group_type = '';
    /**
     *用户类型：user:买家，seller:卖家
     *
     * Generated from protobuf field <code>string user_type = 5;</code>
     */
    protected $user_type = '';
    /**
     *用户等级限制：默认all
     *
     * Generated from protobuf field <code>string user_level = 6;</code>
     */
    protected $user_level = '';
    /**
     *是否领取当天24点失效
     *
     * Generated from protobuf field <code>int32 expire_today = 7;</code>
     */
    protected $expire_today = 0;
    /**
     *自领取时过期的天数
     *
     * Generated from protobuf field <code>int64 expire_days = 8;</code>
     */
    protected $expire_days = 0;
    /**
     *是每天都可领一次，还是总共只能领一次，还是无限制 'everyday','once','free','count_limit'
     *
     * Generated from protobuf field <code>string grant_frequency = 9;</code>
     */
    protected $grant_frequency = '';
    /**
     *每张券每个用户领取数量限制
     *
     * Generated from protobuf field <code>int64 count_limited_per_user = 10;</code>
     */
    protected $count_limited_per_user = 0;
    /**
     *开始时间 时间戳
     *
     * Generated from protobuf field <code>string start_time = 11;</code>
     */
    protected $start_time = '';
    /**
     *结束时间
     *
     * Generated from protobuf field <code>string end_time = 12;</code>
     */
    protected $end_time = '';
    /**
     *
     * Generated from protobuf field <code>string grant_start_time = 13;</code>
     */
    protected $grant_start_time = '';
    /**
     *
     * Generated from protobuf field <code>string grant_end_time = 14;</code>
     */
    protected $grant_end_time = '';
    /**
     *角标图片地址
     *
     * Generated from protobuf field <code>string act_img = 15;</code>
     */
    protected $act_img = '';
    /**
     *用户是否能主动领 0是1否
     *
     * Generated from protobuf field <code>int32 must_grant = 16;</code>
     */
    protected $must_grant = 0;
    /**
     *'all','new_user','old_user','blackcard_user','not_blackcard_user','buyer','not_buyer','seller','not_seller','new_seller','old_seller','cashback','save_money_user','save_money_first_month_user' 发放目标人群
     *
     * Generated from protobuf field <code>string effect_users = 17;</code>
     */
    protected $effect_users = '';
    /**
     *购买金额
     *
     * Generated from protobuf field <code>float price = 18;</code>
     */
    protected $price = 0.0;
    /**
     *券组互斥code
     *
     * Generated from protobuf field <code>string reject_code = 19;</code>
     */
    protected $reject_code = '';
    /**
     *券类型  1新人券
     *
     * Generated from protobuf field <code>int64 voucher_type = 20;</code>
     */
    protected $voucher_type = 0;
    /**
     *归属部门
     *
     * Generated from protobuf field <code>string department = 21;</code>
     */
    protected $department = '';
    /**
     *创建用户id
     *
     * Generated from protobuf field <code>int64 op_id = 22;</code>
     */
    protected $op_id = 0;
    /**
     *优惠券展示页面限制 1在首页展示
     *
     * Generated from protobuf field <code>int32 show_pos = 23;</code>
     */
    protected $show_pos = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *          优惠券组id [选填 有代表更新]
     *     @type string $code
     *          组code
     *     @type string $name
     *          组名字
     *     @type string $group_type
     *          组类型: 优惠券类型，system:系统优惠券，由系统发放给用户；activity：特定活动时给用户
     *     @type string $user_type
     *          用户类型：user:买家，seller:卖家
     *     @type string $user_level
     *          用户等级限制：默认all
     *     @type int $expire_today
     *          是否领取当天24点失效
     *     @type int|string $expire_days
     *          自领取时过期的天数
     *     @type string $grant_frequency
     *          是每天都可领一次，还是总共只能领一次，还是无限制 'everyday','once','free','count_limit'
     *     @type int|string $count_limited_per_user
     *          每张券每个用户领取数量限制
     *     @type string $start_time
     *          开始时间 时间戳
     *     @type string $end_time
     *          结束时间
     *     @type string $grant_start_time
     *     @type string $grant_end_time
     *     @type string $act_img
     *          角标图片地址
     *     @type int $must_grant
     *          用户是否能主动领 0是1否
     *     @type string $effect_users
     *          'all','new_user','old_user','blackcard_user','not_blackcard_user','buyer','not_buyer','seller','not_seller','new_seller','old_seller','cashback','save_money_user','save_money_first_month_user' 发放目标人群
     *     @type float $price
     *          购买金额
     *     @type string $reject_code
     *          券组互斥code
     *     @type int|string $voucher_type
     *          券类型  1新人券
     *     @type string $department
     *          归属部门
     *     @type int|string $op_id
     *          创建用户id
     *     @type int $show_pos
     *          优惠券展示页面限制 1在首页展示
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParam::initOnce();
        parent::__construct($data);
    }

    /**
     *优惠券组id [选填 有代表更新]
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     *优惠券组id [选填 有代表更新]
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     *组code
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     *组code
     *
     * Generated from protobuf field <code>string code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     *组名字
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *组名字
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *组类型: 优惠券类型，system:系统优惠券，由系统发放给用户；activity：特定活动时给用户
     *
     * Generated from protobuf field <code>string group_type = 4;</code>
     * @return string
     */
    public function getGroupType()
    {
        return $this->group_type;
    }

    /**
     *组类型: 优惠券类型，system:系统优惠券，由系统发放给用户；activity：特定活动时给用户
     *
     * Generated from protobuf field <code>string group_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupType($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_type = $var;

        return $this;
    }

    /**
     *用户类型：user:买家，seller:卖家
     *
     * Generated from protobuf field <code>string user_type = 5;</code>
     * @return string
     */
    public function getUserType()
    {
        return $this->user_type;
    }

    /**
     *用户类型：user:买家，seller:卖家
     *
     * Generated from protobuf field <code>string user_type = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUserType($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_type = $var;

        return $this;
    }

    /**
     *用户等级限制：默认all
     *
     * Generated from protobuf field <code>string user_level = 6;</code>
     * @return string
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     *用户等级限制：默认all
     *
     * Generated from protobuf field <code>string user_level = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_level = $var;

        return $this;
    }

    /**
     *是否领取当天24点失效
     *
     * Generated from protobuf field <code>int32 expire_today = 7;</code>
     * @return int
     */
    public function getExpireToday()
    {
        return $this->expire_today;
    }

    /**
     *是否领取当天24点失效
     *
     * Generated from protobuf field <code>int32 expire_today = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setExpireToday($var)
    {
        GPBUtil::checkInt32($var);
        $this->expire_today = $var;

        return $this;
    }

    /**
     *自领取时过期的天数
     *
     * Generated from protobuf field <code>int64 expire_days = 8;</code>
     * @return int|string
     */
    public function getExpireDays()
    {
        return $this->expire_days;
    }

    /**
     *自领取时过期的天数
     *
     * Generated from protobuf field <code>int64 expire_days = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireDays($var)
    {
        GPBUtil::checkInt64($var);
        $this->expire_days = $var;

        return $this;
    }

    /**
     *是每天都可领一次，还是总共只能领一次，还是无限制 'everyday','once','free','count_limit'
     *
     * Generated from protobuf field <code>string grant_frequency = 9;</code>
     * @return string
     */
    public function getGrantFrequency()
    {
        return $this->grant_frequency;
    }

    /**
     *是每天都可领一次，还是总共只能领一次，还是无限制 'everyday','once','free','count_limit'
     *
     * Generated from protobuf field <code>string grant_frequency = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setGrantFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->grant_frequency = $var;

        return $this;
    }

    /**
     *每张券每个用户领取数量限制
     *
     * Generated from protobuf field <code>int64 count_limited_per_user = 10;</code>
     * @return int|string
     */
    public function getCountLimitedPerUser()
    {
        return $this->count_limited_per_user;
    }

    /**
     *每张券每个用户领取数量限制
     *
     * Generated from protobuf field <code>int64 count_limited_per_user = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCountLimitedPerUser($var)
    {
        GPBUtil::checkInt64($var);
        $this->count_limited_per_user = $var;

        return $this;
    }

    /**
     *开始时间 时间戳
     *
     * Generated from protobuf field <code>string start_time = 11;</code>
     * @return string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     *开始时间 时间戳
     *
     * Generated from protobuf field <code>string start_time = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_time = $var;

        return $this;
    }

    /**
     *结束时间
     *
     * Generated from protobuf field <code>string end_time = 12;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     *结束时间
     *
     * Generated from protobuf field <code>string end_time = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_time = $var;

        return $this;
    }

    /**
     *
     * Generated from protobuf field <code>string grant_start_time = 13;</code>
     * @return string
     */
    public function getGrantStartTime()
    {
        return $this->grant_start_time;
    }

    /**
     *
     * Generated from protobuf field <code>string grant_start_time = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setGrantStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->grant_start_time = $var;

        return $this;
    }

    /**
     *
     * Generated from protobuf field <code>string grant_end_time = 14;</code>
     * @return string
     */
    public function getGrantEndTime()
    {
        return $this->grant_end_time;
    }

    /**
     *
     * Generated from protobuf field <code>string grant_end_time = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setGrantEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->grant_end_time = $var;

        return $this;
    }

    /**
     *角标图片地址
     *
     * Generated from protobuf field <code>string act_img = 15;</code>
     * @return string
     */
    public function getActImg()
    {
        return $this->act_img;
    }

    /**
     *角标图片地址
     *
     * Generated from protobuf field <code>string act_img = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setActImg($var)
    {
        GPBUtil::checkString($var, True);
        $this->act_img = $var;

        return $this;
    }

    /**
     *用户是否能主动领 0是1否
     *
     * Generated from protobuf field <code>int32 must_grant = 16;</code>
     * @return int
     */
    public function getMustGrant()
    {
        return $this->must_grant;
    }

    /**
     *用户是否能主动领 0是1否
     *
     * Generated from protobuf field <code>int32 must_grant = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setMustGrant($var)
    {
        GPBUtil::checkInt32($var);
        $this->must_grant = $var;

        return $this;
    }

    /**
     *'all','new_user','old_user','blackcard_user','not_blackcard_user','buyer','not_buyer','seller','not_seller','new_seller','old_seller','cashback','save_money_user','save_money_first_month_user' 发放目标人群
     *
     * Generated from protobuf field <code>string effect_users = 17;</code>
     * @return string
     */
    public function getEffectUsers()
    {
        return $this->effect_users;
    }

    /**
     *'all','new_user','old_user','blackcard_user','not_blackcard_user','buyer','not_buyer','seller','not_seller','new_seller','old_seller','cashback','save_money_user','save_money_first_month_user' 发放目标人群
     *
     * Generated from protobuf field <code>string effect_users = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setEffectUsers($var)
    {
        GPBUtil::checkString($var, True);
        $this->effect_users = $var;

        return $this;
    }

    /**
     *购买金额
     *
     * Generated from protobuf field <code>float price = 18;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     *购买金额
     *
     * Generated from protobuf field <code>float price = 18;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->price = $var;

        return $this;
    }

    /**
     *券组互斥code
     *
     * Generated from protobuf field <code>string reject_code = 19;</code>
     * @return string
     */
    public function getRejectCode()
    {
        return $this->reject_code;
    }

    /**
     *券组互斥code
     *
     * Generated from protobuf field <code>string reject_code = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setRejectCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->reject_code = $var;

        return $this;
    }

    /**
     *券类型  1新人券
     *
     * Generated from protobuf field <code>int64 voucher_type = 20;</code>
     * @return int|string
     */
    public function getVoucherType()
    {
        return $this->voucher_type;
    }

    /**
     *券类型  1新人券
     *
     * Generated from protobuf field <code>int64 voucher_type = 20;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVoucherType($var)
    {
        GPBUtil::checkInt64($var);
        $this->voucher_type = $var;

        return $this;
    }

    /**
     *归属部门
     *
     * Generated from protobuf field <code>string department = 21;</code>
     * @return string
     */
    public function getDepartment()
    {
        return $this->department;
    }

    /**
     *归属部门
     *
     * Generated from protobuf field <code>string department = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setDepartment($var)
    {
        GPBUtil::checkString($var, True);
        $this->department = $var;

        return $this;
    }

    /**
     *创建用户id
     *
     * Generated from protobuf field <code>int64 op_id = 22;</code>
     * @return int|string
     */
    public function getOpId()
    {
        return $this->op_id;
    }

    /**
     *创建用户id
     *
     * Generated from protobuf field <code>int64 op_id = 22;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOpId($var)
    {
        GPBUtil::checkInt64($var);
        $this->op_id = $var;

        return $this;
    }

    /**
     *优惠券展示页面限制 1在首页展示
     *
     * Generated from protobuf field <code>int32 show_pos = 23;</code>
     * @return int
     */
    public function getShowPos()
    {
        return $this->show_pos;
    }

    /**
     *优惠券展示页面限制 1在首页展示
     *
     * Generated from protobuf field <code>int32 show_pos = 23;</code>
     * @param int $var
     * @return $this
     */
    public function setShowPos($var)
    {
        GPBUtil::checkInt32($var);
        $this->show_pos = $var;

        return $this;
    }

}

