<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * 开店宝 - 创建/编辑 优惠券
 *
 * Generated from protobuf message <code>voucher_types.SellerUpdateVoucherRequest</code>
 */
class SellerUpdateVoucherRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * 用户ID
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     */
    protected $user_id = 0;
    /**
     * 劵名称
     *
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * 开始时间
     *
     * Generated from protobuf field <code>int64 start_time = 4;</code>
     */
    protected $start_time = 0;
    /**
     * 结束时间
     *
     * Generated from protobuf field <code>int64 end_time = 5;</code>
     */
    protected $end_time = 0;
    /**
     * 优惠门槛
     *
     * Generated from protobuf field <code>float condition_value = 6;</code>
     */
    protected $condition_value = 0.0;
    /**
     * 优惠金额
     *
     * Generated from protobuf field <code>float benefit_value = 7;</code>
     */
    protected $benefit_value = 0.0;
    /**
     * 总共发放多少张佣金劵
     *
     * Generated from protobuf field <code>int64 total_count = 8;</code>
     */
    protected $total_count = 0;
    /**
     * 操作人员ID
     *
     * Generated from protobuf field <code>int64 op_id = 20;</code>
     */
    protected $op_id = 0;
    /**
     * 操作备注
     *
     * Generated from protobuf field <code>string op_remark = 21;</code>
     */
    protected $op_remark = '';
    /**
     * 角标名称
     *
     * Generated from protobuf field <code>string mark_title = 22;</code>
     */
    protected $mark_title = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           优惠券ID
     *     @type int|string $user_id
     *           用户ID
     *     @type string $name
     *           劵名称
     *     @type int|string $start_time
     *           开始时间
     *     @type int|string $end_time
     *           结束时间
     *     @type float $condition_value
     *           优惠门槛
     *     @type float $benefit_value
     *           优惠金额
     *     @type int|string $total_count
     *           总共发放多少张佣金劵
     *     @type int|string $op_id
     *           操作人员ID
     *     @type string $op_remark
     *           操作备注
     *     @type string $mark_title
     *           角标名称
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParam::initOnce();
        parent::__construct($data);
    }

    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * 用户ID
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * 用户ID
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * 劵名称
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * 劵名称
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * 开始时间
     *
     * Generated from protobuf field <code>int64 start_time = 4;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * 开始时间
     *
     * Generated from protobuf field <code>int64 start_time = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_time = $var;

        return $this;
    }

    /**
     * 结束时间
     *
     * Generated from protobuf field <code>int64 end_time = 5;</code>
     * @return int|string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * 结束时间
     *
     * Generated from protobuf field <code>int64 end_time = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->end_time = $var;

        return $this;
    }

    /**
     * 优惠门槛
     *
     * Generated from protobuf field <code>float condition_value = 6;</code>
     * @return float
     */
    public function getConditionValue()
    {
        return $this->condition_value;
    }

    /**
     * 优惠门槛
     *
     * Generated from protobuf field <code>float condition_value = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setConditionValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->condition_value = $var;

        return $this;
    }

    /**
     * 优惠金额
     *
     * Generated from protobuf field <code>float benefit_value = 7;</code>
     * @return float
     */
    public function getBenefitValue()
    {
        return $this->benefit_value;
    }

    /**
     * 优惠金额
     *
     * Generated from protobuf field <code>float benefit_value = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setBenefitValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->benefit_value = $var;

        return $this;
    }

    /**
     * 总共发放多少张佣金劵
     *
     * Generated from protobuf field <code>int64 total_count = 8;</code>
     * @return int|string
     */
    public function getTotalCount()
    {
        return $this->total_count;
    }

    /**
     * 总共发放多少张佣金劵
     *
     * Generated from protobuf field <code>int64 total_count = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_count = $var;

        return $this;
    }

    /**
     * 操作人员ID
     *
     * Generated from protobuf field <code>int64 op_id = 20;</code>
     * @return int|string
     */
    public function getOpId()
    {
        return $this->op_id;
    }

    /**
     * 操作人员ID
     *
     * Generated from protobuf field <code>int64 op_id = 20;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOpId($var)
    {
        GPBUtil::checkInt64($var);
        $this->op_id = $var;

        return $this;
    }

    /**
     * 操作备注
     *
     * Generated from protobuf field <code>string op_remark = 21;</code>
     * @return string
     */
    public function getOpRemark()
    {
        return $this->op_remark;
    }

    /**
     * 操作备注
     *
     * Generated from protobuf field <code>string op_remark = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setOpRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->op_remark = $var;

        return $this;
    }

    /**
     * 角标名称
     *
     * Generated from protobuf field <code>string mark_title = 22;</code>
     * @return string
     */
    public function getMarkTitle()
    {
        return $this->mark_title;
    }

    /**
     * 角标名称
     *
     * Generated from protobuf field <code>string mark_title = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setMarkTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->mark_title = $var;

        return $this;
    }

}

