<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *发送优惠券-请求
 *
 * Generated from protobuf message <code>voucher_types.SendVoucherRequest</code>
 */
class SendVoucherRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *用户ids [必填]
     *
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     *优惠券id [按优惠券id发送时必填、与voucher_code和group_code互斥]
     *
     * Generated from protobuf field <code>string voucher_id = 2;</code>
     */
    protected $voucher_id = '';
    /**
     *优惠券code [按优惠券code发送时必填、与voucher_id和group_code互斥]
     *
     * Generated from protobuf field <code>string voucher_code = 3;</code>
     */
    protected $voucher_code = '';
    /**
     *优惠券组code [按优惠券组code发送时必填、与voucher_id和voucher_code互斥]
     *
     * Generated from protobuf field <code>string group_code = 4;</code>
     */
    protected $group_code = '';
    /**
     *是否禁止重复领取同一张 [奖励优惠券使用、默认关闭=false、只有voucher_id必填且no_duplicate=true时才有效]
     *
     * Generated from protobuf field <code>bool no_duplicate = 5;</code>
     */
    protected $no_duplicate = false;
    /**
     *来源 [必填 前缀www_、mis_]
     *
     * Generated from protobuf field <code>string source = 6;</code>
     */
    protected $source = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *          用户ids [必填]
     *     @type string $voucher_id
     *          优惠券id [按优惠券id发送时必填、与voucher_code和group_code互斥]
     *     @type string $voucher_code
     *          优惠券code [按优惠券code发送时必填、与voucher_id和group_code互斥]
     *     @type string $group_code
     *          优惠券组code [按优惠券组code发送时必填、与voucher_id和voucher_code互斥]
     *     @type bool $no_duplicate
     *          是否禁止重复领取同一张 [奖励优惠券使用、默认关闭=false、只有voucher_id必填且no_duplicate=true时才有效]
     *     @type string $source
     *          来源 [必填 前缀www_、mis_]
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParam::initOnce();
        parent::__construct($data);
    }

    /**
     *用户ids [必填]
     *
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     *用户ids [必填]
     *
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     *优惠券id [按优惠券id发送时必填、与voucher_code和group_code互斥]
     *
     * Generated from protobuf field <code>string voucher_id = 2;</code>
     * @return string
     */
    public function getVoucherId()
    {
        return $this->voucher_id;
    }

    /**
     *优惠券id [按优惠券id发送时必填、与voucher_code和group_code互斥]
     *
     * Generated from protobuf field <code>string voucher_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVoucherId($var)
    {
        GPBUtil::checkString($var, True);
        $this->voucher_id = $var;

        return $this;
    }

    /**
     *优惠券code [按优惠券code发送时必填、与voucher_id和group_code互斥]
     *
     * Generated from protobuf field <code>string voucher_code = 3;</code>
     * @return string
     */
    public function getVoucherCode()
    {
        return $this->voucher_code;
    }

    /**
     *优惠券code [按优惠券code发送时必填、与voucher_id和group_code互斥]
     *
     * Generated from protobuf field <code>string voucher_code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVoucherCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->voucher_code = $var;

        return $this;
    }

    /**
     *优惠券组code [按优惠券组code发送时必填、与voucher_id和voucher_code互斥]
     *
     * Generated from protobuf field <code>string group_code = 4;</code>
     * @return string
     */
    public function getGroupCode()
    {
        return $this->group_code;
    }

    /**
     *优惠券组code [按优惠券组code发送时必填、与voucher_id和voucher_code互斥]
     *
     * Generated from protobuf field <code>string group_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_code = $var;

        return $this;
    }

    /**
     *是否禁止重复领取同一张 [奖励优惠券使用、默认关闭=false、只有voucher_id必填且no_duplicate=true时才有效]
     *
     * Generated from protobuf field <code>bool no_duplicate = 5;</code>
     * @return bool
     */
    public function getNoDuplicate()
    {
        return $this->no_duplicate;
    }

    /**
     *是否禁止重复领取同一张 [奖励优惠券使用、默认关闭=false、只有voucher_id必填且no_duplicate=true时才有效]
     *
     * Generated from protobuf field <code>bool no_duplicate = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setNoDuplicate($var)
    {
        GPBUtil::checkBool($var);
        $this->no_duplicate = $var;

        return $this;
    }

    /**
     *来源 [必填 前缀www_、mis_]
     *
     * Generated from protobuf field <code>string source = 6;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     *来源 [必填 前缀www_、mis_]
     *
     * Generated from protobuf field <code>string source = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

}

