<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ------------------------------------
 * 公用参数
 * ------------------------------------
 *
 * Generated from protobuf message <code>voucher_types.TUserVoucher</code>
 */
class TUserVoucher extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>int64 voucher_id = 3;</code>
     */
    protected $voucher_id = 0;
    /**
     * Generated from protobuf field <code>int64 voucher_group_id = 4;</code>
     */
    protected $voucher_group_id = 0;
    /**
     * Generated from protobuf field <code>int64 start_time = 5;</code>
     */
    protected $start_time = 0;
    /**
     * Generated from protobuf field <code>int64 end_time = 6;</code>
     */
    protected $end_time = 0;
    /**
     * Generated from protobuf field <code>int32 used = 7;</code>
     */
    protected $used = 0;
    /**
     * Generated from protobuf field <code>int64 used_time = 8;</code>
     */
    protected $used_time = 0;
    /**
     * Generated from protobuf field <code>int64 order_id = 9;</code>
     */
    protected $order_id = 0;
    /**
     * Generated from protobuf field <code>string source = 10;</code>
     */
    protected $source = '';
    /**
     * Generated from protobuf field <code>int32 version = 11;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>int64 create_time = 12;</code>
     */
    protected $create_time = 0;
    /**
     * Generated from protobuf field <code>int64 update_time = 13;</code>
     */
    protected $update_time = 0;
    /**
     * Generated from protobuf field <code>int32 deleted = 14;</code>
     */
    protected $deleted = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $user_id
     *     @type int|string $voucher_id
     *     @type int|string $voucher_group_id
     *     @type int|string $start_time
     *     @type int|string $end_time
     *     @type int $used
     *     @type int|string $used_time
     *     @type int|string $order_id
     *     @type string $source
     *     @type int $version
     *     @type int|string $create_time
     *     @type int|string $update_time
     *     @type int $deleted
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParam::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 voucher_id = 3;</code>
     * @return int|string
     */
    public function getVoucherId()
    {
        return $this->voucher_id;
    }

    /**
     * Generated from protobuf field <code>int64 voucher_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVoucherId($var)
    {
        GPBUtil::checkInt64($var);
        $this->voucher_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 voucher_group_id = 4;</code>
     * @return int|string
     */
    public function getVoucherGroupId()
    {
        return $this->voucher_group_id;
    }

    /**
     * Generated from protobuf field <code>int64 voucher_group_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVoucherGroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->voucher_group_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 start_time = 5;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * Generated from protobuf field <code>int64 start_time = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 end_time = 6;</code>
     * @return int|string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * Generated from protobuf field <code>int64 end_time = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->end_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 used = 7;</code>
     * @return int
     */
    public function getUsed()
    {
        return $this->used;
    }

    /**
     * Generated from protobuf field <code>int32 used = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setUsed($var)
    {
        GPBUtil::checkInt32($var);
        $this->used = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 used_time = 8;</code>
     * @return int|string
     */
    public function getUsedTime()
    {
        return $this->used_time;
    }

    /**
     * Generated from protobuf field <code>int64 used_time = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUsedTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->used_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 order_id = 9;</code>
     * @return int|string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * Generated from protobuf field <code>int64 order_id = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkInt64($var);
        $this->order_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source = 10;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Generated from protobuf field <code>string source = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 version = 11;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int32 version = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 create_time = 12;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * Generated from protobuf field <code>int64 create_time = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->create_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 update_time = 13;</code>
     * @return int|string
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    /**
     * Generated from protobuf field <code>int64 update_time = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->update_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 deleted = 14;</code>
     * @return int
     */
    public function getDeleted()
    {
        return $this->deleted;
    }

    /**
     * Generated from protobuf field <code>int32 deleted = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setDeleted($var)
    {
        GPBUtil::checkInt32($var);
        $this->deleted = $var;

        return $this;
    }

}

