<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * MIS - 创建/编辑 优惠券
 *
 * Generated from protobuf message <code>voucher_types.UpdateVoucherRequest</code>
 */
class UpdateVoucherRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * 优惠券名称
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * 组ID
     *
     * Generated from protobuf field <code>int64 group_id = 3;</code>
     */
    protected $group_id = 0;
    /**
     * 类目ID
     *
     * Generated from protobuf field <code>string category_list = 4;</code>
     */
    protected $category_list = '';
    /**
     * 品牌ID
     *
     * Generated from protobuf field <code>string brand_list = 5;</code>
     */
    protected $brand_list = '';
    /**
     * 适用范围描述
     *
     * Generated from protobuf field <code>string scope_items_text = 6;</code>
     */
    protected $scope_items_text = '';
    /**
     * 在组内获取的概率百分数
     *
     * Generated from protobuf field <code>int32 rate_in_group = 7;</code>
     */
    protected $rate_in_group = 0;
    /**
     * 使用说明
     *
     * Generated from protobuf field <code>string description = 8;</code>
     */
    protected $description = '';
    /**
     * 是否只能用于原价购买的商品
     *
     * Generated from protobuf field <code>int32 nondiscount_only = 9;</code>
     */
    protected $nondiscount_only = 0;
    /**
     * 生效页面1详情页可领取
     *
     * Generated from protobuf field <code>int32 effect_position = 10;</code>
     */
    protected $effect_position = 0;
    /**
     * 生效页面1详情页可领取
     *
     * Generated from protobuf field <code>string effect_users = 11;</code>
     */
    protected $effect_users = '';
    /**
     * 卖家是否承担营销成本
     *
     * Generated from protobuf field <code>int32 seller_support = 12;</code>
     */
    protected $seller_support = 0;
    /**
     * 使用门槛
     *
     * Generated from protobuf field <code>float condition_value = 13;</code>
     */
    protected $condition_value = 0.0;
    /**
     * 优惠金额
     *
     * Generated from protobuf field <code>float benefit_value = 14;</code>
     */
    protected $benefit_value = 0.0;
    /**
     * 领取的口令
     *
     * Generated from protobuf field <code>string code = 15;</code>
     */
    protected $code = '';
    /**
     * 总共发放多少优惠券
     *
     * Generated from protobuf field <code>int64 total_count = 16;</code>
     */
    protected $total_count = 0;
    /**
     * 每日库存
     *
     * Generated from protobuf field <code>repeated string daliy_count = 17;</code>
     */
    private $daliy_count;
    /**
     * 每日库存时间
     *
     * Generated from protobuf field <code>repeated string daliy_time = 18;</code>
     */
    private $daliy_time;
    /**
     * 限定发放数量
     *
     * Generated from protobuf field <code>int32 count_limited = 19;</code>
     */
    protected $count_limited = 0;
    /**
     * 购买金额
     *
     * Generated from protobuf field <code>float price = 20;</code>
     */
    protected $price = 0.0;
    /**
     * 可领取的时间
     *
     * Generated from protobuf field <code>int64 getable_time = 21;</code>
     */
    protected $getable_time = 0;
    /**
     * 开始时间
     *
     * Generated from protobuf field <code>int64 start_time = 22;</code>
     */
    protected $start_time = 0;
    /**
     * 结束时间
     *
     * Generated from protobuf field <code>int64 end_time = 23;</code>
     */
    protected $end_time = 0;
    /**
     * 自领取时过期的天数
     *
     * Generated from protobuf field <code>int64 expire_days = 24;</code>
     */
    protected $expire_days = 0;
    /**
     * 领取当天24点失效
     *
     * Generated from protobuf field <code>int32 expire_today = 25;</code>
     */
    protected $expire_today = 0;
    /**
     * 优惠券绑定商品售出天数
     *
     * Generated from protobuf field <code>int32 sold_days = 26;</code>
     */
    protected $sold_days = 0;
    /**
     * 优惠券绑定商品售出时间
     *
     * Generated from protobuf field <code>int64 sold_time = 27;</code>
     */
    protected $sold_time = 0;
    /**
     * 最高抵扣的金额
     *
     * Generated from protobuf field <code>float max_off_price = 28;</code>
     */
    protected $max_off_price = 0.0;
    /**
     * 卖家id,以,分割
     *
     * Generated from protobuf field <code>string seller_list = 29;</code>
     */
    protected $seller_list = '';
    /**
     * 红豆兑换   0: 默认 >0: 兑换所需红豆
     *
     * Generated from protobuf field <code>int32 integral = 30;</code>
     */
    protected $integral = 0;
    /**
     * 跳转链接
     *
     * Generated from protobuf field <code>string skip_links = 31;</code>
     */
    protected $skip_links = '';
    /**
     * 活动ID,以,分割
     *
     * Generated from protobuf field <code>string activity_list = 32;</code>
     */
    protected $activity_list = '';
    /**
     * 商品类型：all：全部，brandnew：新品，secondhand:二手
     *
     * Generated from protobuf field <code>string product_type = 33;</code>
     */
    protected $product_type = '';
    /**
     * 商品范围。1:全部商品(保留)，2:个人卖家|参加活动，3:个人卖家|不参加活动，4:低价制商品，5:自主定价|优惠券力度0，6:自主定价|优惠券力度5，7:自主定价|优惠券力度8，8:自主定价|优惠券力度10，9:佣金制商品
     *
     * Generated from protobuf field <code>string product_coverage = 34;</code>
     */
    protected $product_coverage = '';
    /**
     * 是否支持清仓商品，1是，0否，默认值0
     *
     * Generated from protobuf field <code>int32 support_clearance = 35;</code>
     */
    protected $support_clearance = 0;
    /**
     * 选定的折扣id,以逗号分隔，当support_clearance设置为1值，此值才生效
     *
     * Generated from protobuf field <code>string discount_ids = 36;</code>
     */
    protected $discount_ids = '';
    /**
     * 领取后几天后可以使用
     *
     * Generated from protobuf field <code>int32 can_use_days = 37;</code>
     */
    protected $can_use_days = 0;
    /**
     * 优惠券业务分类ID, t_voucher_category.id
     *
     * Generated from protobuf field <code>int64 vc_id = 38;</code>
     */
    protected $vc_id = 0;
    /**
     * 自主提报活动ID，多个逗号隔开
     *
     * Generated from protobuf field <code>string seller_applying_config_ids = 39;</code>
     */
    protected $seller_applying_config_ids = '';
    /**
     * 平台自采账号ID，多个逗号隔开
     *
     * Generated from protobuf field <code>string plum_config_ids = 40;</code>
     */
    protected $plum_config_ids = '';
    /**
     * 上架天数下限
     *
     * Generated from protobuf field <code>int32 onsale_day_min = 41;</code>
     */
    protected $onsale_day_min = 0;
    /**
     * 上架天数上限
     *
     * Generated from protobuf field <code>int32 onsale_day_max = 42;</code>
     */
    protected $onsale_day_max = 0;
    /**
     * 商详页是否展示浮动提示 0 不展示 1 展示
     *
     * Generated from protobuf field <code>int32 show_float = 43;</code>
     */
    protected $show_float = 0;
    /**
     * 是否提醒
     *
     * Generated from protobuf field <code>int32 can_notify = 44;</code>
     */
    protected $can_notify = 0;
    /**
     * 优惠券展示页面限制 1在首页展示
     *
     * Generated from protobuf field <code>int32 show_pos = 45;</code>
     */
    protected $show_pos = 0;
    /**
     * 操作人员ID
     *
     * Generated from protobuf field <code>int64 op_id = 46;</code>
     */
    protected $op_id = 0;
    /**
     * 操作备注
     *
     * Generated from protobuf field <code>string op_remark = 47;</code>
     */
    protected $op_remark = '';
    /**
     * 商品类型
     *
     * Generated from protobuf field <code>string provider_type = 48;</code>
     */
    protected $provider_type = '';
    /**
     * 自定义活动页ID，多个逗号隔开
     *
     * Generated from protobuf field <code>string page_ids = 49;</code>
     */
    protected $page_ids = '';
    /**
     * 是否展示（只在新人页的新人券展示时判断）
     *
     * Generated from protobuf field <code>int32 is_show = 50;</code>
     */
    protected $is_show = 0;
    /**
     * 角标名称
     *
     * Generated from protobuf field <code>string mark_title = 51;</code>
     */
    protected $mark_title = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           优惠券ID
     *     @type string $name
     *           优惠券名称
     *     @type int|string $group_id
     *           组ID
     *     @type string $category_list
     *           类目ID
     *     @type string $brand_list
     *           品牌ID
     *     @type string $scope_items_text
     *           适用范围描述
     *     @type int $rate_in_group
     *           在组内获取的概率百分数
     *     @type string $description
     *           使用说明
     *     @type int $nondiscount_only
     *           是否只能用于原价购买的商品
     *     @type int $effect_position
     *           生效页面1详情页可领取
     *     @type string $effect_users
     *           生效页面1详情页可领取
     *     @type int $seller_support
     *           卖家是否承担营销成本
     *     @type float $condition_value
     *           使用门槛
     *     @type float $benefit_value
     *           优惠金额
     *     @type string $code
     *           领取的口令
     *     @type int|string $total_count
     *           总共发放多少优惠券
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $daliy_count
     *           每日库存
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $daliy_time
     *           每日库存时间
     *     @type int $count_limited
     *           限定发放数量
     *     @type float $price
     *           购买金额
     *     @type int|string $getable_time
     *           可领取的时间
     *     @type int|string $start_time
     *           开始时间
     *     @type int|string $end_time
     *           结束时间
     *     @type int|string $expire_days
     *           自领取时过期的天数
     *     @type int $expire_today
     *           领取当天24点失效
     *     @type int $sold_days
     *           优惠券绑定商品售出天数
     *     @type int|string $sold_time
     *           优惠券绑定商品售出时间
     *     @type float $max_off_price
     *           最高抵扣的金额
     *     @type string $seller_list
     *           卖家id,以,分割
     *     @type int $integral
     *           红豆兑换   0: 默认 >0: 兑换所需红豆
     *     @type string $skip_links
     *           跳转链接
     *     @type string $activity_list
     *           活动ID,以,分割
     *     @type string $product_type
     *           商品类型：all：全部，brandnew：新品，secondhand:二手
     *     @type string $product_coverage
     *           商品范围。1:全部商品(保留)，2:个人卖家|参加活动，3:个人卖家|不参加活动，4:低价制商品，5:自主定价|优惠券力度0，6:自主定价|优惠券力度5，7:自主定价|优惠券力度8，8:自主定价|优惠券力度10，9:佣金制商品
     *     @type int $support_clearance
     *           是否支持清仓商品，1是，0否，默认值0
     *     @type string $discount_ids
     *           选定的折扣id,以逗号分隔，当support_clearance设置为1值，此值才生效
     *     @type int $can_use_days
     *           领取后几天后可以使用
     *     @type int|string $vc_id
     *           优惠券业务分类ID, t_voucher_category.id
     *     @type string $seller_applying_config_ids
     *           自主提报活动ID，多个逗号隔开
     *     @type string $plum_config_ids
     *           平台自采账号ID，多个逗号隔开
     *     @type int $onsale_day_min
     *           上架天数下限
     *     @type int $onsale_day_max
     *           上架天数上限
     *     @type int $show_float
     *           商详页是否展示浮动提示 0 不展示 1 展示
     *     @type int $can_notify
     *           是否提醒
     *     @type int $show_pos
     *           优惠券展示页面限制 1在首页展示
     *     @type int|string $op_id
     *           操作人员ID
     *     @type string $op_remark
     *           操作备注
     *     @type string $provider_type
     *           商品类型
     *     @type string $page_ids
     *           自定义活动页ID，多个逗号隔开
     *     @type int $is_show
     *           是否展示（只在新人页的新人券展示时判断）
     *     @type string $mark_title
     *           角标名称
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParam::initOnce();
        parent::__construct($data);
    }

    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * 优惠券名称
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * 优惠券名称
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * 组ID
     *
     * Generated from protobuf field <code>int64 group_id = 3;</code>
     * @return int|string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * 组ID
     *
     * Generated from protobuf field <code>int64 group_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->group_id = $var;

        return $this;
    }

    /**
     * 类目ID
     *
     * Generated from protobuf field <code>string category_list = 4;</code>
     * @return string
     */
    public function getCategoryList()
    {
        return $this->category_list;
    }

    /**
     * 类目ID
     *
     * Generated from protobuf field <code>string category_list = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryList($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_list = $var;

        return $this;
    }

    /**
     * 品牌ID
     *
     * Generated from protobuf field <code>string brand_list = 5;</code>
     * @return string
     */
    public function getBrandList()
    {
        return $this->brand_list;
    }

    /**
     * 品牌ID
     *
     * Generated from protobuf field <code>string brand_list = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBrandList($var)
    {
        GPBUtil::checkString($var, True);
        $this->brand_list = $var;

        return $this;
    }

    /**
     * 适用范围描述
     *
     * Generated from protobuf field <code>string scope_items_text = 6;</code>
     * @return string
     */
    public function getScopeItemsText()
    {
        return $this->scope_items_text;
    }

    /**
     * 适用范围描述
     *
     * Generated from protobuf field <code>string scope_items_text = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setScopeItemsText($var)
    {
        GPBUtil::checkString($var, True);
        $this->scope_items_text = $var;

        return $this;
    }

    /**
     * 在组内获取的概率百分数
     *
     * Generated from protobuf field <code>int32 rate_in_group = 7;</code>
     * @return int
     */
    public function getRateInGroup()
    {
        return $this->rate_in_group;
    }

    /**
     * 在组内获取的概率百分数
     *
     * Generated from protobuf field <code>int32 rate_in_group = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setRateInGroup($var)
    {
        GPBUtil::checkInt32($var);
        $this->rate_in_group = $var;

        return $this;
    }

    /**
     * 使用说明
     *
     * Generated from protobuf field <code>string description = 8;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * 使用说明
     *
     * Generated from protobuf field <code>string description = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * 是否只能用于原价购买的商品
     *
     * Generated from protobuf field <code>int32 nondiscount_only = 9;</code>
     * @return int
     */
    public function getNondiscountOnly()
    {
        return $this->nondiscount_only;
    }

    /**
     * 是否只能用于原价购买的商品
     *
     * Generated from protobuf field <code>int32 nondiscount_only = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setNondiscountOnly($var)
    {
        GPBUtil::checkInt32($var);
        $this->nondiscount_only = $var;

        return $this;
    }

    /**
     * 生效页面1详情页可领取
     *
     * Generated from protobuf field <code>int32 effect_position = 10;</code>
     * @return int
     */
    public function getEffectPosition()
    {
        return $this->effect_position;
    }

    /**
     * 生效页面1详情页可领取
     *
     * Generated from protobuf field <code>int32 effect_position = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setEffectPosition($var)
    {
        GPBUtil::checkInt32($var);
        $this->effect_position = $var;

        return $this;
    }

    /**
     * 生效页面1详情页可领取
     *
     * Generated from protobuf field <code>string effect_users = 11;</code>
     * @return string
     */
    public function getEffectUsers()
    {
        return $this->effect_users;
    }

    /**
     * 生效页面1详情页可领取
     *
     * Generated from protobuf field <code>string effect_users = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setEffectUsers($var)
    {
        GPBUtil::checkString($var, True);
        $this->effect_users = $var;

        return $this;
    }

    /**
     * 卖家是否承担营销成本
     *
     * Generated from protobuf field <code>int32 seller_support = 12;</code>
     * @return int
     */
    public function getSellerSupport()
    {
        return $this->seller_support;
    }

    /**
     * 卖家是否承担营销成本
     *
     * Generated from protobuf field <code>int32 seller_support = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setSellerSupport($var)
    {
        GPBUtil::checkInt32($var);
        $this->seller_support = $var;

        return $this;
    }

    /**
     * 使用门槛
     *
     * Generated from protobuf field <code>float condition_value = 13;</code>
     * @return float
     */
    public function getConditionValue()
    {
        return $this->condition_value;
    }

    /**
     * 使用门槛
     *
     * Generated from protobuf field <code>float condition_value = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setConditionValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->condition_value = $var;

        return $this;
    }

    /**
     * 优惠金额
     *
     * Generated from protobuf field <code>float benefit_value = 14;</code>
     * @return float
     */
    public function getBenefitValue()
    {
        return $this->benefit_value;
    }

    /**
     * 优惠金额
     *
     * Generated from protobuf field <code>float benefit_value = 14;</code>
     * @param float $var
     * @return $this
     */
    public function setBenefitValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->benefit_value = $var;

        return $this;
    }

    /**
     * 领取的口令
     *
     * Generated from protobuf field <code>string code = 15;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * 领取的口令
     *
     * Generated from protobuf field <code>string code = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * 总共发放多少优惠券
     *
     * Generated from protobuf field <code>int64 total_count = 16;</code>
     * @return int|string
     */
    public function getTotalCount()
    {
        return $this->total_count;
    }

    /**
     * 总共发放多少优惠券
     *
     * Generated from protobuf field <code>int64 total_count = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_count = $var;

        return $this;
    }

    /**
     * 每日库存
     *
     * Generated from protobuf field <code>repeated string daliy_count = 17;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDaliyCount()
    {
        return $this->daliy_count;
    }

    /**
     * 每日库存
     *
     * Generated from protobuf field <code>repeated string daliy_count = 17;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDaliyCount($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->daliy_count = $arr;

        return $this;
    }

    /**
     * 每日库存时间
     *
     * Generated from protobuf field <code>repeated string daliy_time = 18;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDaliyTime()
    {
        return $this->daliy_time;
    }

    /**
     * 每日库存时间
     *
     * Generated from protobuf field <code>repeated string daliy_time = 18;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDaliyTime($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->daliy_time = $arr;

        return $this;
    }

    /**
     * 限定发放数量
     *
     * Generated from protobuf field <code>int32 count_limited = 19;</code>
     * @return int
     */
    public function getCountLimited()
    {
        return $this->count_limited;
    }

    /**
     * 限定发放数量
     *
     * Generated from protobuf field <code>int32 count_limited = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setCountLimited($var)
    {
        GPBUtil::checkInt32($var);
        $this->count_limited = $var;

        return $this;
    }

    /**
     * 购买金额
     *
     * Generated from protobuf field <code>float price = 20;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * 购买金额
     *
     * Generated from protobuf field <code>float price = 20;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->price = $var;

        return $this;
    }

    /**
     * 可领取的时间
     *
     * Generated from protobuf field <code>int64 getable_time = 21;</code>
     * @return int|string
     */
    public function getGetableTime()
    {
        return $this->getable_time;
    }

    /**
     * 可领取的时间
     *
     * Generated from protobuf field <code>int64 getable_time = 21;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGetableTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->getable_time = $var;

        return $this;
    }

    /**
     * 开始时间
     *
     * Generated from protobuf field <code>int64 start_time = 22;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * 开始时间
     *
     * Generated from protobuf field <code>int64 start_time = 22;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_time = $var;

        return $this;
    }

    /**
     * 结束时间
     *
     * Generated from protobuf field <code>int64 end_time = 23;</code>
     * @return int|string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * 结束时间
     *
     * Generated from protobuf field <code>int64 end_time = 23;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->end_time = $var;

        return $this;
    }

    /**
     * 自领取时过期的天数
     *
     * Generated from protobuf field <code>int64 expire_days = 24;</code>
     * @return int|string
     */
    public function getExpireDays()
    {
        return $this->expire_days;
    }

    /**
     * 自领取时过期的天数
     *
     * Generated from protobuf field <code>int64 expire_days = 24;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireDays($var)
    {
        GPBUtil::checkInt64($var);
        $this->expire_days = $var;

        return $this;
    }

    /**
     * 领取当天24点失效
     *
     * Generated from protobuf field <code>int32 expire_today = 25;</code>
     * @return int
     */
    public function getExpireToday()
    {
        return $this->expire_today;
    }

    /**
     * 领取当天24点失效
     *
     * Generated from protobuf field <code>int32 expire_today = 25;</code>
     * @param int $var
     * @return $this
     */
    public function setExpireToday($var)
    {
        GPBUtil::checkInt32($var);
        $this->expire_today = $var;

        return $this;
    }

    /**
     * 优惠券绑定商品售出天数
     *
     * Generated from protobuf field <code>int32 sold_days = 26;</code>
     * @return int
     */
    public function getSoldDays()
    {
        return $this->sold_days;
    }

    /**
     * 优惠券绑定商品售出天数
     *
     * Generated from protobuf field <code>int32 sold_days = 26;</code>
     * @param int $var
     * @return $this
     */
    public function setSoldDays($var)
    {
        GPBUtil::checkInt32($var);
        $this->sold_days = $var;

        return $this;
    }

    /**
     * 优惠券绑定商品售出时间
     *
     * Generated from protobuf field <code>int64 sold_time = 27;</code>
     * @return int|string
     */
    public function getSoldTime()
    {
        return $this->sold_time;
    }

    /**
     * 优惠券绑定商品售出时间
     *
     * Generated from protobuf field <code>int64 sold_time = 27;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSoldTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->sold_time = $var;

        return $this;
    }

    /**
     * 最高抵扣的金额
     *
     * Generated from protobuf field <code>float max_off_price = 28;</code>
     * @return float
     */
    public function getMaxOffPrice()
    {
        return $this->max_off_price;
    }

    /**
     * 最高抵扣的金额
     *
     * Generated from protobuf field <code>float max_off_price = 28;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxOffPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->max_off_price = $var;

        return $this;
    }

    /**
     * 卖家id,以,分割
     *
     * Generated from protobuf field <code>string seller_list = 29;</code>
     * @return string
     */
    public function getSellerList()
    {
        return $this->seller_list;
    }

    /**
     * 卖家id,以,分割
     *
     * Generated from protobuf field <code>string seller_list = 29;</code>
     * @param string $var
     * @return $this
     */
    public function setSellerList($var)
    {
        GPBUtil::checkString($var, True);
        $this->seller_list = $var;

        return $this;
    }

    /**
     * 红豆兑换   0: 默认 >0: 兑换所需红豆
     *
     * Generated from protobuf field <code>int32 integral = 30;</code>
     * @return int
     */
    public function getIntegral()
    {
        return $this->integral;
    }

    /**
     * 红豆兑换   0: 默认 >0: 兑换所需红豆
     *
     * Generated from protobuf field <code>int32 integral = 30;</code>
     * @param int $var
     * @return $this
     */
    public function setIntegral($var)
    {
        GPBUtil::checkInt32($var);
        $this->integral = $var;

        return $this;
    }

    /**
     * 跳转链接
     *
     * Generated from protobuf field <code>string skip_links = 31;</code>
     * @return string
     */
    public function getSkipLinks()
    {
        return $this->skip_links;
    }

    /**
     * 跳转链接
     *
     * Generated from protobuf field <code>string skip_links = 31;</code>
     * @param string $var
     * @return $this
     */
    public function setSkipLinks($var)
    {
        GPBUtil::checkString($var, True);
        $this->skip_links = $var;

        return $this;
    }

    /**
     * 活动ID,以,分割
     *
     * Generated from protobuf field <code>string activity_list = 32;</code>
     * @return string
     */
    public function getActivityList()
    {
        return $this->activity_list;
    }

    /**
     * 活动ID,以,分割
     *
     * Generated from protobuf field <code>string activity_list = 32;</code>
     * @param string $var
     * @return $this
     */
    public function setActivityList($var)
    {
        GPBUtil::checkString($var, True);
        $this->activity_list = $var;

        return $this;
    }

    /**
     * 商品类型：all：全部，brandnew：新品，secondhand:二手
     *
     * Generated from protobuf field <code>string product_type = 33;</code>
     * @return string
     */
    public function getProductType()
    {
        return $this->product_type;
    }

    /**
     * 商品类型：all：全部，brandnew：新品，secondhand:二手
     *
     * Generated from protobuf field <code>string product_type = 33;</code>
     * @param string $var
     * @return $this
     */
    public function setProductType($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_type = $var;

        return $this;
    }

    /**
     * 商品范围。1:全部商品(保留)，2:个人卖家|参加活动，3:个人卖家|不参加活动，4:低价制商品，5:自主定价|优惠券力度0，6:自主定价|优惠券力度5，7:自主定价|优惠券力度8，8:自主定价|优惠券力度10，9:佣金制商品
     *
     * Generated from protobuf field <code>string product_coverage = 34;</code>
     * @return string
     */
    public function getProductCoverage()
    {
        return $this->product_coverage;
    }

    /**
     * 商品范围。1:全部商品(保留)，2:个人卖家|参加活动，3:个人卖家|不参加活动，4:低价制商品，5:自主定价|优惠券力度0，6:自主定价|优惠券力度5，7:自主定价|优惠券力度8，8:自主定价|优惠券力度10，9:佣金制商品
     *
     * Generated from protobuf field <code>string product_coverage = 34;</code>
     * @param string $var
     * @return $this
     */
    public function setProductCoverage($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_coverage = $var;

        return $this;
    }

    /**
     * 是否支持清仓商品，1是，0否，默认值0
     *
     * Generated from protobuf field <code>int32 support_clearance = 35;</code>
     * @return int
     */
    public function getSupportClearance()
    {
        return $this->support_clearance;
    }

    /**
     * 是否支持清仓商品，1是，0否，默认值0
     *
     * Generated from protobuf field <code>int32 support_clearance = 35;</code>
     * @param int $var
     * @return $this
     */
    public function setSupportClearance($var)
    {
        GPBUtil::checkInt32($var);
        $this->support_clearance = $var;

        return $this;
    }

    /**
     * 选定的折扣id,以逗号分隔，当support_clearance设置为1值，此值才生效
     *
     * Generated from protobuf field <code>string discount_ids = 36;</code>
     * @return string
     */
    public function getDiscountIds()
    {
        return $this->discount_ids;
    }

    /**
     * 选定的折扣id,以逗号分隔，当support_clearance设置为1值，此值才生效
     *
     * Generated from protobuf field <code>string discount_ids = 36;</code>
     * @param string $var
     * @return $this
     */
    public function setDiscountIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->discount_ids = $var;

        return $this;
    }

    /**
     * 领取后几天后可以使用
     *
     * Generated from protobuf field <code>int32 can_use_days = 37;</code>
     * @return int
     */
    public function getCanUseDays()
    {
        return $this->can_use_days;
    }

    /**
     * 领取后几天后可以使用
     *
     * Generated from protobuf field <code>int32 can_use_days = 37;</code>
     * @param int $var
     * @return $this
     */
    public function setCanUseDays($var)
    {
        GPBUtil::checkInt32($var);
        $this->can_use_days = $var;

        return $this;
    }

    /**
     * 优惠券业务分类ID, t_voucher_category.id
     *
     * Generated from protobuf field <code>int64 vc_id = 38;</code>
     * @return int|string
     */
    public function getVcId()
    {
        return $this->vc_id;
    }

    /**
     * 优惠券业务分类ID, t_voucher_category.id
     *
     * Generated from protobuf field <code>int64 vc_id = 38;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVcId($var)
    {
        GPBUtil::checkInt64($var);
        $this->vc_id = $var;

        return $this;
    }

    /**
     * 自主提报活动ID，多个逗号隔开
     *
     * Generated from protobuf field <code>string seller_applying_config_ids = 39;</code>
     * @return string
     */
    public function getSellerApplyingConfigIds()
    {
        return $this->seller_applying_config_ids;
    }

    /**
     * 自主提报活动ID，多个逗号隔开
     *
     * Generated from protobuf field <code>string seller_applying_config_ids = 39;</code>
     * @param string $var
     * @return $this
     */
    public function setSellerApplyingConfigIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->seller_applying_config_ids = $var;

        return $this;
    }

    /**
     * 平台自采账号ID，多个逗号隔开
     *
     * Generated from protobuf field <code>string plum_config_ids = 40;</code>
     * @return string
     */
    public function getPlumConfigIds()
    {
        return $this->plum_config_ids;
    }

    /**
     * 平台自采账号ID，多个逗号隔开
     *
     * Generated from protobuf field <code>string plum_config_ids = 40;</code>
     * @param string $var
     * @return $this
     */
    public function setPlumConfigIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->plum_config_ids = $var;

        return $this;
    }

    /**
     * 上架天数下限
     *
     * Generated from protobuf field <code>int32 onsale_day_min = 41;</code>
     * @return int
     */
    public function getOnsaleDayMin()
    {
        return $this->onsale_day_min;
    }

    /**
     * 上架天数下限
     *
     * Generated from protobuf field <code>int32 onsale_day_min = 41;</code>
     * @param int $var
     * @return $this
     */
    public function setOnsaleDayMin($var)
    {
        GPBUtil::checkInt32($var);
        $this->onsale_day_min = $var;

        return $this;
    }

    /**
     * 上架天数上限
     *
     * Generated from protobuf field <code>int32 onsale_day_max = 42;</code>
     * @return int
     */
    public function getOnsaleDayMax()
    {
        return $this->onsale_day_max;
    }

    /**
     * 上架天数上限
     *
     * Generated from protobuf field <code>int32 onsale_day_max = 42;</code>
     * @param int $var
     * @return $this
     */
    public function setOnsaleDayMax($var)
    {
        GPBUtil::checkInt32($var);
        $this->onsale_day_max = $var;

        return $this;
    }

    /**
     * 商详页是否展示浮动提示 0 不展示 1 展示
     *
     * Generated from protobuf field <code>int32 show_float = 43;</code>
     * @return int
     */
    public function getShowFloat()
    {
        return $this->show_float;
    }

    /**
     * 商详页是否展示浮动提示 0 不展示 1 展示
     *
     * Generated from protobuf field <code>int32 show_float = 43;</code>
     * @param int $var
     * @return $this
     */
    public function setShowFloat($var)
    {
        GPBUtil::checkInt32($var);
        $this->show_float = $var;

        return $this;
    }

    /**
     * 是否提醒
     *
     * Generated from protobuf field <code>int32 can_notify = 44;</code>
     * @return int
     */
    public function getCanNotify()
    {
        return $this->can_notify;
    }

    /**
     * 是否提醒
     *
     * Generated from protobuf field <code>int32 can_notify = 44;</code>
     * @param int $var
     * @return $this
     */
    public function setCanNotify($var)
    {
        GPBUtil::checkInt32($var);
        $this->can_notify = $var;

        return $this;
    }

    /**
     * 优惠券展示页面限制 1在首页展示
     *
     * Generated from protobuf field <code>int32 show_pos = 45;</code>
     * @return int
     */
    public function getShowPos()
    {
        return $this->show_pos;
    }

    /**
     * 优惠券展示页面限制 1在首页展示
     *
     * Generated from protobuf field <code>int32 show_pos = 45;</code>
     * @param int $var
     * @return $this
     */
    public function setShowPos($var)
    {
        GPBUtil::checkInt32($var);
        $this->show_pos = $var;

        return $this;
    }

    /**
     * 操作人员ID
     *
     * Generated from protobuf field <code>int64 op_id = 46;</code>
     * @return int|string
     */
    public function getOpId()
    {
        return $this->op_id;
    }

    /**
     * 操作人员ID
     *
     * Generated from protobuf field <code>int64 op_id = 46;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOpId($var)
    {
        GPBUtil::checkInt64($var);
        $this->op_id = $var;

        return $this;
    }

    /**
     * 操作备注
     *
     * Generated from protobuf field <code>string op_remark = 47;</code>
     * @return string
     */
    public function getOpRemark()
    {
        return $this->op_remark;
    }

    /**
     * 操作备注
     *
     * Generated from protobuf field <code>string op_remark = 47;</code>
     * @param string $var
     * @return $this
     */
    public function setOpRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->op_remark = $var;

        return $this;
    }

    /**
     * 商品类型
     *
     * Generated from protobuf field <code>string provider_type = 48;</code>
     * @return string
     */
    public function getProviderType()
    {
        return $this->provider_type;
    }

    /**
     * 商品类型
     *
     * Generated from protobuf field <code>string provider_type = 48;</code>
     * @param string $var
     * @return $this
     */
    public function setProviderType($var)
    {
        GPBUtil::checkString($var, True);
        $this->provider_type = $var;

        return $this;
    }

    /**
     * 自定义活动页ID，多个逗号隔开
     *
     * Generated from protobuf field <code>string page_ids = 49;</code>
     * @return string
     */
    public function getPageIds()
    {
        return $this->page_ids;
    }

    /**
     * 自定义活动页ID，多个逗号隔开
     *
     * Generated from protobuf field <code>string page_ids = 49;</code>
     * @param string $var
     * @return $this
     */
    public function setPageIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_ids = $var;

        return $this;
    }

    /**
     * 是否展示（只在新人页的新人券展示时判断）
     *
     * Generated from protobuf field <code>int32 is_show = 50;</code>
     * @return int
     */
    public function getIsShow()
    {
        return $this->is_show;
    }

    /**
     * 是否展示（只在新人页的新人券展示时判断）
     *
     * Generated from protobuf field <code>int32 is_show = 50;</code>
     * @param int $var
     * @return $this
     */
    public function setIsShow($var)
    {
        GPBUtil::checkInt32($var);
        $this->is_show = $var;

        return $this;
    }

    /**
     * 角标名称
     *
     * Generated from protobuf field <code>string mark_title = 51;</code>
     * @return string
     */
    public function getMarkTitle()
    {
        return $this->mark_title;
    }

    /**
     * 角标名称
     *
     * Generated from protobuf field <code>string mark_title = 51;</code>
     * @param string $var
     * @return $this
     */
    public function setMarkTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->mark_title = $var;

        return $this;
    }

}

