<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * 创建/编辑 优惠券组
 *
 * Generated from protobuf message <code>voucher_types.UpdateVoucherGroupRequest</code>
 */
class UpdateVoucherGroupRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 优惠券组ID(编辑时传)
     *
     * Generated from protobuf field <code>int64 voucher_group_id = 1;</code>
     */
    protected $voucher_group_id = 0;
    /**
     * 劵组名称
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * 劵组Code
     *
     * Generated from protobuf field <code>string code = 3;</code>
     */
    protected $code = '';
    /**
     * 买家券组互斥码：newborn(买家新人券-券包组)、orderReturn(买家新人券-返现组)、cashback_b(买家新人券-返现组（弃用）)、firstOrderSellerVoucher(新人首单寄卖券)
     *
     * Generated from protobuf field <code>string reject_code = 4;</code>
     */
    protected $reject_code = '';
    /**
     * 开始时间
     *
     * Generated from protobuf field <code>int64 start_time = 5;</code>
     */
    protected $start_time = 0;
    /**
     * 结束时间
     *
     * Generated from protobuf field <code>int64 end_time = 6;</code>
     */
    protected $end_time = 0;
    /**
     * 发放频率：once（只领一次）、everyday（每天最多一次）、free（无限制）、count_limit（用户领取数量）
     *
     * Generated from protobuf field <code>string grant_frequency = 7;</code>
     */
    protected $grant_frequency = '';
    /**
     * 用户是否能主动领 0是 1否
     *
     * Generated from protobuf field <code>int32 must_grant = 8;</code>
     */
    protected $must_grant = 0;
    /**
     * 购买金额
     *
     * Generated from protobuf field <code>float price = 9;</code>
     */
    protected $price = 0.0;
    /**
     * 发放人群：all(所有用户)、new_user(新用户)、old_user(非新用户)、blackcard_user(黑卡用户)、not_blackcard_user(非黑卡用户)、buyer(买家)、not_buyer(非买家)、seller(卖家)、not_seller(非卖家)、new_seller(新卖家)、old_seller(老卖家)、cashback(新人返现组)、save_money_user(省钱卡用户)、save_money_first_month_user(省钱卡首月用户)
     *
     * Generated from protobuf field <code>string effect_users = 10;</code>
     */
    protected $effect_users = '';
    /**
     * 用户等级，默认all
     *
     * Generated from protobuf field <code>string user_level = 11;</code>
     */
    protected $user_level = '';
    /**
     * 劵组所属的部门：csd(客服-客服)、app_user(商城-用户组)、app_activity(商城-活动组)、brand_bd(品牌-BD)、market_hbl(市场-私域)、plum_live(直播)、merchant(卖家自播)、hr(人力行政)
     *
     * Generated from protobuf field <code>string department = 12;</code>
     */
    protected $department = '';
    /**
     * 显示角标
     *
     * Generated from protobuf field <code>string act_img = 13;</code>
     */
    protected $act_img = '';
    /**
     * 是否浮层可见
     *
     * Generated from protobuf field <code>int32 show_pos = 14;</code>
     */
    protected $show_pos = 0;
    /**
     * 用户类型：user:买家，seller:卖家
     *
     * Generated from protobuf field <code>string user_type = 15;</code>
     */
    protected $user_type = '';
    /**
     * 每张券每个用户领取数量限制
     *
     * Generated from protobuf field <code>int64 count_limited_per_user = 16;</code>
     */
    protected $count_limited_per_user = 0;
    /**
     * 券类型  1新人券
     *
     * Generated from protobuf field <code>float voucher_type = 17;</code>
     */
    protected $voucher_type = 0.0;
    /**
     * 复制操作，复制组ID
     *
     * Generated from protobuf field <code>int64 copy_group_id = 18;</code>
     */
    protected $copy_group_id = 0;
    /**
     * 操作人员ID
     *
     * Generated from protobuf field <code>int64 op_id = 30;</code>
     */
    protected $op_id = 0;
    /**
     * 操作备注
     *
     * Generated from protobuf field <code>string op_remark = 31;</code>
     */
    protected $op_remark = '';
    /**
     * 角标名称
     *
     * Generated from protobuf field <code>string mark_title = 32;</code>
     */
    protected $mark_title = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $voucher_group_id
     *           优惠券组ID(编辑时传)
     *     @type string $name
     *           劵组名称
     *     @type string $code
     *           劵组Code
     *     @type string $reject_code
     *           买家券组互斥码：newborn(买家新人券-券包组)、orderReturn(买家新人券-返现组)、cashback_b(买家新人券-返现组（弃用）)、firstOrderSellerVoucher(新人首单寄卖券)
     *     @type int|string $start_time
     *           开始时间
     *     @type int|string $end_time
     *           结束时间
     *     @type string $grant_frequency
     *           发放频率：once（只领一次）、everyday（每天最多一次）、free（无限制）、count_limit（用户领取数量）
     *     @type int $must_grant
     *           用户是否能主动领 0是 1否
     *     @type float $price
     *           购买金额
     *     @type string $effect_users
     *           发放人群：all(所有用户)、new_user(新用户)、old_user(非新用户)、blackcard_user(黑卡用户)、not_blackcard_user(非黑卡用户)、buyer(买家)、not_buyer(非买家)、seller(卖家)、not_seller(非卖家)、new_seller(新卖家)、old_seller(老卖家)、cashback(新人返现组)、save_money_user(省钱卡用户)、save_money_first_month_user(省钱卡首月用户)
     *     @type string $user_level
     *           用户等级，默认all
     *     @type string $department
     *           劵组所属的部门：csd(客服-客服)、app_user(商城-用户组)、app_activity(商城-活动组)、brand_bd(品牌-BD)、market_hbl(市场-私域)、plum_live(直播)、merchant(卖家自播)、hr(人力行政)
     *     @type string $act_img
     *           显示角标
     *     @type int $show_pos
     *           是否浮层可见
     *     @type string $user_type
     *           用户类型：user:买家，seller:卖家
     *     @type int|string $count_limited_per_user
     *           每张券每个用户领取数量限制
     *     @type float $voucher_type
     *           券类型  1新人券
     *     @type int|string $copy_group_id
     *           复制操作，复制组ID
     *     @type int|string $op_id
     *           操作人员ID
     *     @type string $op_remark
     *           操作备注
     *     @type string $mark_title
     *           角标名称
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParam::initOnce();
        parent::__construct($data);
    }

    /**
     * 优惠券组ID(编辑时传)
     *
     * Generated from protobuf field <code>int64 voucher_group_id = 1;</code>
     * @return int|string
     */
    public function getVoucherGroupId()
    {
        return $this->voucher_group_id;
    }

    /**
     * 优惠券组ID(编辑时传)
     *
     * Generated from protobuf field <code>int64 voucher_group_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVoucherGroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->voucher_group_id = $var;

        return $this;
    }

    /**
     * 劵组名称
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * 劵组名称
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * 劵组Code
     *
     * Generated from protobuf field <code>string code = 3;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * 劵组Code
     *
     * Generated from protobuf field <code>string code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * 买家券组互斥码：newborn(买家新人券-券包组)、orderReturn(买家新人券-返现组)、cashback_b(买家新人券-返现组（弃用）)、firstOrderSellerVoucher(新人首单寄卖券)
     *
     * Generated from protobuf field <code>string reject_code = 4;</code>
     * @return string
     */
    public function getRejectCode()
    {
        return $this->reject_code;
    }

    /**
     * 买家券组互斥码：newborn(买家新人券-券包组)、orderReturn(买家新人券-返现组)、cashback_b(买家新人券-返现组（弃用）)、firstOrderSellerVoucher(新人首单寄卖券)
     *
     * Generated from protobuf field <code>string reject_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRejectCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->reject_code = $var;

        return $this;
    }

    /**
     * 开始时间
     *
     * Generated from protobuf field <code>int64 start_time = 5;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * 开始时间
     *
     * Generated from protobuf field <code>int64 start_time = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_time = $var;

        return $this;
    }

    /**
     * 结束时间
     *
     * Generated from protobuf field <code>int64 end_time = 6;</code>
     * @return int|string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * 结束时间
     *
     * Generated from protobuf field <code>int64 end_time = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->end_time = $var;

        return $this;
    }

    /**
     * 发放频率：once（只领一次）、everyday（每天最多一次）、free（无限制）、count_limit（用户领取数量）
     *
     * Generated from protobuf field <code>string grant_frequency = 7;</code>
     * @return string
     */
    public function getGrantFrequency()
    {
        return $this->grant_frequency;
    }

    /**
     * 发放频率：once（只领一次）、everyday（每天最多一次）、free（无限制）、count_limit（用户领取数量）
     *
     * Generated from protobuf field <code>string grant_frequency = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setGrantFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->grant_frequency = $var;

        return $this;
    }

    /**
     * 用户是否能主动领 0是 1否
     *
     * Generated from protobuf field <code>int32 must_grant = 8;</code>
     * @return int
     */
    public function getMustGrant()
    {
        return $this->must_grant;
    }

    /**
     * 用户是否能主动领 0是 1否
     *
     * Generated from protobuf field <code>int32 must_grant = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setMustGrant($var)
    {
        GPBUtil::checkInt32($var);
        $this->must_grant = $var;

        return $this;
    }

    /**
     * 购买金额
     *
     * Generated from protobuf field <code>float price = 9;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * 购买金额
     *
     * Generated from protobuf field <code>float price = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->price = $var;

        return $this;
    }

    /**
     * 发放人群：all(所有用户)、new_user(新用户)、old_user(非新用户)、blackcard_user(黑卡用户)、not_blackcard_user(非黑卡用户)、buyer(买家)、not_buyer(非买家)、seller(卖家)、not_seller(非卖家)、new_seller(新卖家)、old_seller(老卖家)、cashback(新人返现组)、save_money_user(省钱卡用户)、save_money_first_month_user(省钱卡首月用户)
     *
     * Generated from protobuf field <code>string effect_users = 10;</code>
     * @return string
     */
    public function getEffectUsers()
    {
        return $this->effect_users;
    }

    /**
     * 发放人群：all(所有用户)、new_user(新用户)、old_user(非新用户)、blackcard_user(黑卡用户)、not_blackcard_user(非黑卡用户)、buyer(买家)、not_buyer(非买家)、seller(卖家)、not_seller(非卖家)、new_seller(新卖家)、old_seller(老卖家)、cashback(新人返现组)、save_money_user(省钱卡用户)、save_money_first_month_user(省钱卡首月用户)
     *
     * Generated from protobuf field <code>string effect_users = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setEffectUsers($var)
    {
        GPBUtil::checkString($var, True);
        $this->effect_users = $var;

        return $this;
    }

    /**
     * 用户等级，默认all
     *
     * Generated from protobuf field <code>string user_level = 11;</code>
     * @return string
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * 用户等级，默认all
     *
     * Generated from protobuf field <code>string user_level = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_level = $var;

        return $this;
    }

    /**
     * 劵组所属的部门：csd(客服-客服)、app_user(商城-用户组)、app_activity(商城-活动组)、brand_bd(品牌-BD)、market_hbl(市场-私域)、plum_live(直播)、merchant(卖家自播)、hr(人力行政)
     *
     * Generated from protobuf field <code>string department = 12;</code>
     * @return string
     */
    public function getDepartment()
    {
        return $this->department;
    }

    /**
     * 劵组所属的部门：csd(客服-客服)、app_user(商城-用户组)、app_activity(商城-活动组)、brand_bd(品牌-BD)、market_hbl(市场-私域)、plum_live(直播)、merchant(卖家自播)、hr(人力行政)
     *
     * Generated from protobuf field <code>string department = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setDepartment($var)
    {
        GPBUtil::checkString($var, True);
        $this->department = $var;

        return $this;
    }

    /**
     * 显示角标
     *
     * Generated from protobuf field <code>string act_img = 13;</code>
     * @return string
     */
    public function getActImg()
    {
        return $this->act_img;
    }

    /**
     * 显示角标
     *
     * Generated from protobuf field <code>string act_img = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setActImg($var)
    {
        GPBUtil::checkString($var, True);
        $this->act_img = $var;

        return $this;
    }

    /**
     * 是否浮层可见
     *
     * Generated from protobuf field <code>int32 show_pos = 14;</code>
     * @return int
     */
    public function getShowPos()
    {
        return $this->show_pos;
    }

    /**
     * 是否浮层可见
     *
     * Generated from protobuf field <code>int32 show_pos = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setShowPos($var)
    {
        GPBUtil::checkInt32($var);
        $this->show_pos = $var;

        return $this;
    }

    /**
     * 用户类型：user:买家，seller:卖家
     *
     * Generated from protobuf field <code>string user_type = 15;</code>
     * @return string
     */
    public function getUserType()
    {
        return $this->user_type;
    }

    /**
     * 用户类型：user:买家，seller:卖家
     *
     * Generated from protobuf field <code>string user_type = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setUserType($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_type = $var;

        return $this;
    }

    /**
     * 每张券每个用户领取数量限制
     *
     * Generated from protobuf field <code>int64 count_limited_per_user = 16;</code>
     * @return int|string
     */
    public function getCountLimitedPerUser()
    {
        return $this->count_limited_per_user;
    }

    /**
     * 每张券每个用户领取数量限制
     *
     * Generated from protobuf field <code>int64 count_limited_per_user = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCountLimitedPerUser($var)
    {
        GPBUtil::checkInt64($var);
        $this->count_limited_per_user = $var;

        return $this;
    }

    /**
     * 券类型  1新人券
     *
     * Generated from protobuf field <code>float voucher_type = 17;</code>
     * @return float
     */
    public function getVoucherType()
    {
        return $this->voucher_type;
    }

    /**
     * 券类型  1新人券
     *
     * Generated from protobuf field <code>float voucher_type = 17;</code>
     * @param float $var
     * @return $this
     */
    public function setVoucherType($var)
    {
        GPBUtil::checkFloat($var);
        $this->voucher_type = $var;

        return $this;
    }

    /**
     * 复制操作，复制组ID
     *
     * Generated from protobuf field <code>int64 copy_group_id = 18;</code>
     * @return int|string
     */
    public function getCopyGroupId()
    {
        return $this->copy_group_id;
    }

    /**
     * 复制操作，复制组ID
     *
     * Generated from protobuf field <code>int64 copy_group_id = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCopyGroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->copy_group_id = $var;

        return $this;
    }

    /**
     * 操作人员ID
     *
     * Generated from protobuf field <code>int64 op_id = 30;</code>
     * @return int|string
     */
    public function getOpId()
    {
        return $this->op_id;
    }

    /**
     * 操作人员ID
     *
     * Generated from protobuf field <code>int64 op_id = 30;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOpId($var)
    {
        GPBUtil::checkInt64($var);
        $this->op_id = $var;

        return $this;
    }

    /**
     * 操作备注
     *
     * Generated from protobuf field <code>string op_remark = 31;</code>
     * @return string
     */
    public function getOpRemark()
    {
        return $this->op_remark;
    }

    /**
     * 操作备注
     *
     * Generated from protobuf field <code>string op_remark = 31;</code>
     * @param string $var
     * @return $this
     */
    public function setOpRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->op_remark = $var;

        return $this;
    }

    /**
     * 角标名称
     *
     * Generated from protobuf field <code>string mark_title = 32;</code>
     * @return string
     */
    public function getMarkTitle()
    {
        return $this->mark_title;
    }

    /**
     * 角标名称
     *
     * Generated from protobuf field <code>string mark_title = 32;</code>
     * @param string $var
     * @return $this
     */
    public function setMarkTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->mark_title = $var;

        return $this;
    }

}

