<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>voucher_types.UserVoucherDelayResponse</code>
 */
class UserVoucherDelayResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 code = 1;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     */
    protected $msg = '';
    /**
     * Generated from protobuf field <code>.voucher_types.TUserVoucher user_voucher = 3;</code>
     */
    protected $user_voucher = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $code
     *     @type string $msg
     *     @type \app\components\proto\voucher\TUserVoucher $user_voucher
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParam::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 code = 1;</code>
     * @return int|string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int64 code = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt64($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.voucher_types.TUserVoucher user_voucher = 3;</code>
     * @return \app\components\proto\voucher\TUserVoucher|null
     */
    public function getUserVoucher()
    {
        return isset($this->user_voucher) ? $this->user_voucher : null;
    }

    public function hasUserVoucher()
    {
        return isset($this->user_voucher);
    }

    public function clearUserVoucher()
    {
        unset($this->user_voucher);
    }

    /**
     * Generated from protobuf field <code>.voucher_types.TUserVoucher user_voucher = 3;</code>
     * @param \app\components\proto\voucher\TUserVoucher $var
     * @return $this
     */
    public function setUserVoucher($var)
    {
        GPBUtil::checkMessage($var, \app\components\proto\voucher\TUserVoucher::class);
        $this->user_voucher = $var;

        return $this;
    }

}

