<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param-read.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 获取用户券data
 *
 * Generated from protobuf message <code>voucher_types_read.UserVoucherData</code>
 */
class UserVoucherData extends \Google\Protobuf\Internal\Message
{
    /**
     * 用户券ID
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * 用户ID
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     */
    protected $user_id = 0;
    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>int64 voucher_id = 3;</code>
     */
    protected $voucher_id = 0;
    /**
     * 优惠券组ID
     *
     * Generated from protobuf field <code>int64 voucher_group_id = 4;</code>
     */
    protected $voucher_group_id = 0;
    /**
     * 开始时间
     *
     * Generated from protobuf field <code>int64 start_time = 5;</code>
     */
    protected $start_time = 0;
    /**
     * 结束时间
     *
     * Generated from protobuf field <code>int64 end_time = 6;</code>
     */
    protected $end_time = 0;
    /**
     * 是否使用
     *
     * Generated from protobuf field <code>int64 used = 7;</code>
     */
    protected $used = 0;
    /**
     * 使用时间
     *
     * Generated from protobuf field <code>int64 used_time = 8;</code>
     */
    protected $used_time = 0;
    /**
     * 订单ID
     *
     * Generated from protobuf field <code>int64 order_id = 9;</code>
     */
    protected $order_id = 0;
    /**
     * 来源
     *
     * Generated from protobuf field <code>string source = 10;</code>
     */
    protected $source = '';
    /**
     * 版本
     *
     * Generated from protobuf field <code>int64 version = 11;</code>
     */
    protected $version = 0;
    /**
     * 领取时间
     *
     * Generated from protobuf field <code>int64 create_time = 12;</code>
     */
    protected $create_time = 0;
    /**
     * 修改时间
     *
     * Generated from protobuf field <code>int64 update_time = 13;</code>
     */
    protected $update_time = 0;
    /**
     * 优惠券信息
     *
     * Generated from protobuf field <code>.voucher_types_read.VoucherData voucher = 14;</code>
     */
    protected $voucher = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           用户券ID
     *     @type int|string $user_id
     *           用户ID
     *     @type int|string $voucher_id
     *           优惠券ID
     *     @type int|string $voucher_group_id
     *           优惠券组ID
     *     @type int|string $start_time
     *           开始时间
     *     @type int|string $end_time
     *           结束时间
     *     @type int|string $used
     *           是否使用
     *     @type int|string $used_time
     *           使用时间
     *     @type int|string $order_id
     *           订单ID
     *     @type string $source
     *           来源
     *     @type int|string $version
     *           版本
     *     @type int|string $create_time
     *           领取时间
     *     @type int|string $update_time
     *           修改时间
     *     @type \app\components\proto\voucher\VoucherData $voucher
     *           优惠券信息
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParamRead::initOnce();
        parent::__construct($data);
    }

    /**
     * 用户券ID
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * 用户券ID
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * 用户ID
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * 用户ID
     *
     * Generated from protobuf field <code>int64 user_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>int64 voucher_id = 3;</code>
     * @return int|string
     */
    public function getVoucherId()
    {
        return $this->voucher_id;
    }

    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>int64 voucher_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVoucherId($var)
    {
        GPBUtil::checkInt64($var);
        $this->voucher_id = $var;

        return $this;
    }

    /**
     * 优惠券组ID
     *
     * Generated from protobuf field <code>int64 voucher_group_id = 4;</code>
     * @return int|string
     */
    public function getVoucherGroupId()
    {
        return $this->voucher_group_id;
    }

    /**
     * 优惠券组ID
     *
     * Generated from protobuf field <code>int64 voucher_group_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVoucherGroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->voucher_group_id = $var;

        return $this;
    }

    /**
     * 开始时间
     *
     * Generated from protobuf field <code>int64 start_time = 5;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * 开始时间
     *
     * Generated from protobuf field <code>int64 start_time = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_time = $var;

        return $this;
    }

    /**
     * 结束时间
     *
     * Generated from protobuf field <code>int64 end_time = 6;</code>
     * @return int|string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * 结束时间
     *
     * Generated from protobuf field <code>int64 end_time = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->end_time = $var;

        return $this;
    }

    /**
     * 是否使用
     *
     * Generated from protobuf field <code>int64 used = 7;</code>
     * @return int|string
     */
    public function getUsed()
    {
        return $this->used;
    }

    /**
     * 是否使用
     *
     * Generated from protobuf field <code>int64 used = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUsed($var)
    {
        GPBUtil::checkInt64($var);
        $this->used = $var;

        return $this;
    }

    /**
     * 使用时间
     *
     * Generated from protobuf field <code>int64 used_time = 8;</code>
     * @return int|string
     */
    public function getUsedTime()
    {
        return $this->used_time;
    }

    /**
     * 使用时间
     *
     * Generated from protobuf field <code>int64 used_time = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUsedTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->used_time = $var;

        return $this;
    }

    /**
     * 订单ID
     *
     * Generated from protobuf field <code>int64 order_id = 9;</code>
     * @return int|string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * 订单ID
     *
     * Generated from protobuf field <code>int64 order_id = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkInt64($var);
        $this->order_id = $var;

        return $this;
    }

    /**
     * 来源
     *
     * Generated from protobuf field <code>string source = 10;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * 来源
     *
     * Generated from protobuf field <code>string source = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

    /**
     * 版本
     *
     * Generated from protobuf field <code>int64 version = 11;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * 版本
     *
     * Generated from protobuf field <code>int64 version = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * 领取时间
     *
     * Generated from protobuf field <code>int64 create_time = 12;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * 领取时间
     *
     * Generated from protobuf field <code>int64 create_time = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->create_time = $var;

        return $this;
    }

    /**
     * 修改时间
     *
     * Generated from protobuf field <code>int64 update_time = 13;</code>
     * @return int|string
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    /**
     * 修改时间
     *
     * Generated from protobuf field <code>int64 update_time = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->update_time = $var;

        return $this;
    }

    /**
     * 优惠券信息
     *
     * Generated from protobuf field <code>.voucher_types_read.VoucherData voucher = 14;</code>
     * @return \app\components\proto\voucher\VoucherData|null
     */
    public function getVoucher()
    {
        return isset($this->voucher) ? $this->voucher : null;
    }

    public function hasVoucher()
    {
        return isset($this->voucher);
    }

    public function clearVoucher()
    {
        unset($this->voucher);
    }

    /**
     * 优惠券信息
     *
     * Generated from protobuf field <code>.voucher_types_read.VoucherData voucher = 14;</code>
     * @param \app\components\proto\voucher\VoucherData $var
     * @return $this
     */
    public function setVoucher($var)
    {
        GPBUtil::checkMessage($var, \app\components\proto\voucher\VoucherData::class);
        $this->voucher = $var;

        return $this;
    }

}

