<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param-read.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>voucher_types_read.VoucherGroupData</code>
 */
class VoucherGroupData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string code = 3;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>string group_type = 4;</code>
     */
    protected $group_type = '';
    /**
     * Generated from protobuf field <code>string user_type = 5;</code>
     */
    protected $user_type = '';
    /**
     * Generated from protobuf field <code>string user_level = 6;</code>
     */
    protected $user_level = '';
    /**
     * Generated from protobuf field <code>int64 expire_today = 7;</code>
     */
    protected $expire_today = 0;
    /**
     * Generated from protobuf field <code>int64 expire_days = 8;</code>
     */
    protected $expire_days = 0;
    /**
     * Generated from protobuf field <code>string grant_frequency = 9;</code>
     */
    protected $grant_frequency = '';
    /**
     * Generated from protobuf field <code>int64 count_limited_per_user = 10;</code>
     */
    protected $count_limited_per_user = 0;
    /**
     * Generated from protobuf field <code>int64 start_time = 11;</code>
     */
    protected $start_time = 0;
    /**
     * Generated from protobuf field <code>int64 end_time = 12;</code>
     */
    protected $end_time = 0;
    /**
     * Generated from protobuf field <code>int64 grant_start_time = 13;</code>
     */
    protected $grant_start_time = 0;
    /**
     * Generated from protobuf field <code>int64 grant_end_time = 14;</code>
     */
    protected $grant_end_time = 0;
    /**
     * Generated from protobuf field <code>string act_img = 15;</code>
     */
    protected $act_img = '';
    /**
     * Generated from protobuf field <code>int64 must_grant = 16;</code>
     */
    protected $must_grant = 0;
    /**
     * Generated from protobuf field <code>int64 create_time = 17;</code>
     */
    protected $create_time = 0;
    /**
     * Generated from protobuf field <code>int64 update_time = 18;</code>
     */
    protected $update_time = 0;
    /**
     * Generated from protobuf field <code>string effect_users = 19;</code>
     */
    protected $effect_users = '';
    /**
     * Generated from protobuf field <code>float price = 20;</code>
     */
    protected $price = 0.0;
    /**
     * Generated from protobuf field <code>string reject_code = 21;</code>
     */
    protected $reject_code = '';
    /**
     * Generated from protobuf field <code>int64 voucher_type = 22;</code>
     */
    protected $voucher_type = 0;
    /**
     * Generated from protobuf field <code>string department = 23;</code>
     */
    protected $department = '';
    /**
     * Generated from protobuf field <code>int64 op_id = 24;</code>
     */
    protected $op_id = 0;
    /**
     * Generated from protobuf field <code>int64 show_pos = 25;</code>
     */
    protected $show_pos = 0;
    /**
     * 角标名称
     *
     * Generated from protobuf field <code>string mark_title = 26;</code>
     */
    protected $mark_title = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $name
     *     @type string $code
     *     @type string $group_type
     *     @type string $user_type
     *     @type string $user_level
     *     @type int|string $expire_today
     *     @type int|string $expire_days
     *     @type string $grant_frequency
     *     @type int|string $count_limited_per_user
     *     @type int|string $start_time
     *     @type int|string $end_time
     *     @type int|string $grant_start_time
     *     @type int|string $grant_end_time
     *     @type string $act_img
     *     @type int|string $must_grant
     *     @type int|string $create_time
     *     @type int|string $update_time
     *     @type string $effect_users
     *     @type float $price
     *     @type string $reject_code
     *     @type int|string $voucher_type
     *     @type string $department
     *     @type int|string $op_id
     *     @type int|string $show_pos
     *     @type string $mark_title
     *           角标名称
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParamRead::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string group_type = 4;</code>
     * @return string
     */
    public function getGroupType()
    {
        return $this->group_type;
    }

    /**
     * Generated from protobuf field <code>string group_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupType($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_type = 5;</code>
     * @return string
     */
    public function getUserType()
    {
        return $this->user_type;
    }

    /**
     * Generated from protobuf field <code>string user_type = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUserType($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_level = 6;</code>
     * @return string
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * Generated from protobuf field <code>string user_level = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expire_today = 7;</code>
     * @return int|string
     */
    public function getExpireToday()
    {
        return $this->expire_today;
    }

    /**
     * Generated from protobuf field <code>int64 expire_today = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireToday($var)
    {
        GPBUtil::checkInt64($var);
        $this->expire_today = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expire_days = 8;</code>
     * @return int|string
     */
    public function getExpireDays()
    {
        return $this->expire_days;
    }

    /**
     * Generated from protobuf field <code>int64 expire_days = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireDays($var)
    {
        GPBUtil::checkInt64($var);
        $this->expire_days = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string grant_frequency = 9;</code>
     * @return string
     */
    public function getGrantFrequency()
    {
        return $this->grant_frequency;
    }

    /**
     * Generated from protobuf field <code>string grant_frequency = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setGrantFrequency($var)
    {
        GPBUtil::checkString($var, True);
        $this->grant_frequency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 count_limited_per_user = 10;</code>
     * @return int|string
     */
    public function getCountLimitedPerUser()
    {
        return $this->count_limited_per_user;
    }

    /**
     * Generated from protobuf field <code>int64 count_limited_per_user = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCountLimitedPerUser($var)
    {
        GPBUtil::checkInt64($var);
        $this->count_limited_per_user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 start_time = 11;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * Generated from protobuf field <code>int64 start_time = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 end_time = 12;</code>
     * @return int|string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * Generated from protobuf field <code>int64 end_time = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->end_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 grant_start_time = 13;</code>
     * @return int|string
     */
    public function getGrantStartTime()
    {
        return $this->grant_start_time;
    }

    /**
     * Generated from protobuf field <code>int64 grant_start_time = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGrantStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->grant_start_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 grant_end_time = 14;</code>
     * @return int|string
     */
    public function getGrantEndTime()
    {
        return $this->grant_end_time;
    }

    /**
     * Generated from protobuf field <code>int64 grant_end_time = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGrantEndTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->grant_end_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string act_img = 15;</code>
     * @return string
     */
    public function getActImg()
    {
        return $this->act_img;
    }

    /**
     * Generated from protobuf field <code>string act_img = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setActImg($var)
    {
        GPBUtil::checkString($var, True);
        $this->act_img = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 must_grant = 16;</code>
     * @return int|string
     */
    public function getMustGrant()
    {
        return $this->must_grant;
    }

    /**
     * Generated from protobuf field <code>int64 must_grant = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMustGrant($var)
    {
        GPBUtil::checkInt64($var);
        $this->must_grant = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 create_time = 17;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * Generated from protobuf field <code>int64 create_time = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->create_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 update_time = 18;</code>
     * @return int|string
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    /**
     * Generated from protobuf field <code>int64 update_time = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->update_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string effect_users = 19;</code>
     * @return string
     */
    public function getEffectUsers()
    {
        return $this->effect_users;
    }

    /**
     * Generated from protobuf field <code>string effect_users = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setEffectUsers($var)
    {
        GPBUtil::checkString($var, True);
        $this->effect_users = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float price = 20;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>float price = 20;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reject_code = 21;</code>
     * @return string
     */
    public function getRejectCode()
    {
        return $this->reject_code;
    }

    /**
     * Generated from protobuf field <code>string reject_code = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setRejectCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->reject_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 voucher_type = 22;</code>
     * @return int|string
     */
    public function getVoucherType()
    {
        return $this->voucher_type;
    }

    /**
     * Generated from protobuf field <code>int64 voucher_type = 22;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVoucherType($var)
    {
        GPBUtil::checkInt64($var);
        $this->voucher_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string department = 23;</code>
     * @return string
     */
    public function getDepartment()
    {
        return $this->department;
    }

    /**
     * Generated from protobuf field <code>string department = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setDepartment($var)
    {
        GPBUtil::checkString($var, True);
        $this->department = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 op_id = 24;</code>
     * @return int|string
     */
    public function getOpId()
    {
        return $this->op_id;
    }

    /**
     * Generated from protobuf field <code>int64 op_id = 24;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOpId($var)
    {
        GPBUtil::checkInt64($var);
        $this->op_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 show_pos = 25;</code>
     * @return int|string
     */
    public function getShowPos()
    {
        return $this->show_pos;
    }

    /**
     * Generated from protobuf field <code>int64 show_pos = 25;</code>
     * @param int|string $var
     * @return $this
     */
    public function setShowPos($var)
    {
        GPBUtil::checkInt64($var);
        $this->show_pos = $var;

        return $this;
    }

    /**
     * 角标名称
     *
     * Generated from protobuf field <code>string mark_title = 26;</code>
     * @return string
     */
    public function getMarkTitle()
    {
        return $this->mark_title;
    }

    /**
     * 角标名称
     *
     * Generated from protobuf field <code>string mark_title = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setMarkTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->mark_title = $var;

        return $this;
    }

}

