<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param-read.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 券data，字短描述参考表结构
 *
 * Generated from protobuf message <code>voucher_types_read.VoucherData</code>
 */
class VoucherData extends \Google\Protobuf\Internal\Message
{
    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>int64 voucher_id = 1;</code>
     */
    protected $voucher_id = 0;
    /**
     * 优惠券名字
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * 券组ID
     *
     * Generated from protobuf field <code>int64 group_id = 3;</code>
     */
    protected $group_id = 0;
    /**
     * 券类型
     *
     * Generated from protobuf field <code>string voucher_type = 4;</code>
     */
    protected $voucher_type = '';
    /**
     * 券新版类型
     *
     * Generated from protobuf field <code>string voucher_cate = 5;</code>
     */
    protected $voucher_cate = '';
    /**
     * 用户类型
     *
     * Generated from protobuf field <code>string user_type = 6;</code>
     */
    protected $user_type = '';
    /**
     * 用户等级
     *
     * Generated from protobuf field <code>string user_level = 7;</code>
     */
    protected $user_level = '';
    /**
     * 分类ID
     *
     * Generated from protobuf field <code>string category_list = 8;</code>
     */
    protected $category_list = '';
    /**
     * 商品id
     *
     * Generated from protobuf field <code>string brand_list = 9;</code>
     */
    protected $brand_list = '';
    /**
     * 关联的ID，品牌ID
     *
     * Generated from protobuf field <code>string relation_id = 10;</code>
     */
    protected $relation_id = '';
    /**
     * 商品类型
     *
     * Generated from protobuf field <code>string provider_type = 11;</code>
     */
    protected $provider_type = '';
    /**
     * 适用范围描述
     *
     * Generated from protobuf field <code>string scope_items_text = 12;</code>
     */
    protected $scope_items_text = '';
    /**
     * 在组内获取的概率百分数
     *
     * Generated from protobuf field <code>int64 rate_in_group = 13;</code>
     */
    protected $rate_in_group = 0;
    /**
     * 使用说明
     *
     * Generated from protobuf field <code>string description = 14;</code>
     */
    protected $description = '';
    /**
     * 是否只能用于原价购买的商品
     *
     * Generated from protobuf field <code>int64 nondiscount_only = 15;</code>
     */
    protected $nondiscount_only = 0;
    /**
     * Generated from protobuf field <code>int64 effect_position = 16;</code>
     */
    protected $effect_position = 0;
    /**
     * Generated from protobuf field <code>string effect_users = 17;</code>
     */
    protected $effect_users = '';
    /**
     * Generated from protobuf field <code>int64 seller_support = 18;</code>
     */
    protected $seller_support = 0;
    /**
     * Generated from protobuf field <code>float condition_value = 19;</code>
     */
    protected $condition_value = 0.0;
    /**
     * Generated from protobuf field <code>float benefit_value = 20;</code>
     */
    protected $benefit_value = 0.0;
    /**
     * Generated from protobuf field <code>string code = 21;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>int64 total_count = 22;</code>
     */
    protected $total_count = 0;
    /**
     * Generated from protobuf field <code>int64 draw_count = 23;</code>
     */
    protected $draw_count = 0;
    /**
     * Generated from protobuf field <code>string daliy_info = 24;</code>
     */
    protected $daliy_info = '';
    /**
     * Generated from protobuf field <code>int64 count_limited = 25;</code>
     */
    protected $count_limited = 0;
    /**
     * Generated from protobuf field <code>int64 used_count = 26;</code>
     */
    protected $used_count = 0;
    /**
     * Generated from protobuf field <code>float price = 27;</code>
     */
    protected $price = 0.0;
    /**
     * Generated from protobuf field <code>int64 getable_time = 28;</code>
     */
    protected $getable_time = 0;
    /**
     * Generated from protobuf field <code>int64 start_time = 29;</code>
     */
    protected $start_time = 0;
    /**
     * Generated from protobuf field <code>int64 end_time = 30;</code>
     */
    protected $end_time = 0;
    /**
     * Generated from protobuf field <code>int64 expire_days = 31;</code>
     */
    protected $expire_days = 0;
    /**
     * Generated from protobuf field <code>int64 expire_today = 32;</code>
     */
    protected $expire_today = 0;
    /**
     * Generated from protobuf field <code>int64 sold_days = 33;</code>
     */
    protected $sold_days = 0;
    /**
     * Generated from protobuf field <code>int64 sold_time = 34;</code>
     */
    protected $sold_time = 0;
    /**
     * Generated from protobuf field <code>string act_img = 35;</code>
     */
    protected $act_img = '';
    /**
     * Generated from protobuf field <code>int64 enabled = 36;</code>
     */
    protected $enabled = 0;
    /**
     * Generated from protobuf field <code>int64 must_grant = 37;</code>
     */
    protected $must_grant = 0;
    /**
     * Generated from protobuf field <code>int64 create_time = 38;</code>
     */
    protected $create_time = 0;
    /**
     * Generated from protobuf field <code>int64 update_time = 39;</code>
     */
    protected $update_time = 0;
    /**
     * Generated from protobuf field <code>float max_off_price = 40;</code>
     */
    protected $max_off_price = 0.0;
    /**
     * Generated from protobuf field <code>string seller_list = 41;</code>
     */
    protected $seller_list = '';
    /**
     * Generated from protobuf field <code>int64 integral = 42;</code>
     */
    protected $integral = 0;
    /**
     * Generated from protobuf field <code>string skip_links = 43;</code>
     */
    protected $skip_links = '';
    /**
     * Generated from protobuf field <code>string activity_list = 44;</code>
     */
    protected $activity_list = '';
    /**
     * Generated from protobuf field <code>string product_type = 45;</code>
     */
    protected $product_type = '';
    /**
     * Generated from protobuf field <code>string product_coverage = 46;</code>
     */
    protected $product_coverage = '';
    /**
     * Generated from protobuf field <code>int64 support_clearance = 47;</code>
     */
    protected $support_clearance = 0;
    /**
     * Generated from protobuf field <code>string discount_ids = 48;</code>
     */
    protected $discount_ids = '';
    /**
     * Generated from protobuf field <code>int64 can_use_days = 49;</code>
     */
    protected $can_use_days = 0;
    /**
     * Generated from protobuf field <code>int64 vc_id = 50;</code>
     */
    protected $vc_id = 0;
    /**
     * Generated from protobuf field <code>string seller_applying_config_ids = 51;</code>
     */
    protected $seller_applying_config_ids = '';
    /**
     * Generated from protobuf field <code>string plum_config_ids = 52;</code>
     */
    protected $plum_config_ids = '';
    /**
     * Generated from protobuf field <code>string page_ids = 53;</code>
     */
    protected $page_ids = '';
    /**
     * Generated from protobuf field <code>int64 onsale_day_min = 54;</code>
     */
    protected $onsale_day_min = 0;
    /**
     * Generated from protobuf field <code>int64 onsale_day_max = 55;</code>
     */
    protected $onsale_day_max = 0;
    /**
     * Generated from protobuf field <code>int64 show_float = 56;</code>
     */
    protected $show_float = 0;
    /**
     * Generated from protobuf field <code>int64 can_notify = 57;</code>
     */
    protected $can_notify = 0;
    /**
     * Generated from protobuf field <code>int64 show_pos = 58;</code>
     */
    protected $show_pos = 0;
    /**
     * Generated from protobuf field <code>int64 op_id = 59;</code>
     */
    protected $op_id = 0;
    /**
     * Generated from protobuf field <code>int64 version = 60;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>int64 is_show = 61;</code>
     */
    protected $is_show = 0;
    /**
     * 角标名称
     *
     * Generated from protobuf field <code>string mark_title = 62;</code>
     */
    protected $mark_title = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $voucher_id
     *           优惠券ID
     *     @type string $name
     *           优惠券名字
     *     @type int|string $group_id
     *           券组ID
     *     @type string $voucher_type
     *           券类型
     *     @type string $voucher_cate
     *           券新版类型
     *     @type string $user_type
     *           用户类型
     *     @type string $user_level
     *           用户等级
     *     @type string $category_list
     *           分类ID
     *     @type string $brand_list
     *           商品id
     *     @type string $relation_id
     *           关联的ID，品牌ID
     *     @type string $provider_type
     *           商品类型
     *     @type string $scope_items_text
     *           适用范围描述
     *     @type int|string $rate_in_group
     *           在组内获取的概率百分数
     *     @type string $description
     *           使用说明
     *     @type int|string $nondiscount_only
     *           是否只能用于原价购买的商品
     *     @type int|string $effect_position
     *     @type string $effect_users
     *     @type int|string $seller_support
     *     @type float $condition_value
     *     @type float $benefit_value
     *     @type string $code
     *     @type int|string $total_count
     *     @type int|string $draw_count
     *     @type string $daliy_info
     *     @type int|string $count_limited
     *     @type int|string $used_count
     *     @type float $price
     *     @type int|string $getable_time
     *     @type int|string $start_time
     *     @type int|string $end_time
     *     @type int|string $expire_days
     *     @type int|string $expire_today
     *     @type int|string $sold_days
     *     @type int|string $sold_time
     *     @type string $act_img
     *     @type int|string $enabled
     *     @type int|string $must_grant
     *     @type int|string $create_time
     *     @type int|string $update_time
     *     @type float $max_off_price
     *     @type string $seller_list
     *     @type int|string $integral
     *     @type string $skip_links
     *     @type string $activity_list
     *     @type string $product_type
     *     @type string $product_coverage
     *     @type int|string $support_clearance
     *     @type string $discount_ids
     *     @type int|string $can_use_days
     *     @type int|string $vc_id
     *     @type string $seller_applying_config_ids
     *     @type string $plum_config_ids
     *     @type string $page_ids
     *     @type int|string $onsale_day_min
     *     @type int|string $onsale_day_max
     *     @type int|string $show_float
     *     @type int|string $can_notify
     *     @type int|string $show_pos
     *     @type int|string $op_id
     *     @type int|string $version
     *     @type int|string $is_show
     *     @type string $mark_title
     *           角标名称
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParamRead::initOnce();
        parent::__construct($data);
    }

    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>int64 voucher_id = 1;</code>
     * @return int|string
     */
    public function getVoucherId()
    {
        return $this->voucher_id;
    }

    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>int64 voucher_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVoucherId($var)
    {
        GPBUtil::checkInt64($var);
        $this->voucher_id = $var;

        return $this;
    }

    /**
     * 优惠券名字
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * 优惠券名字
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * 券组ID
     *
     * Generated from protobuf field <code>int64 group_id = 3;</code>
     * @return int|string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * 券组ID
     *
     * Generated from protobuf field <code>int64 group_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->group_id = $var;

        return $this;
    }

    /**
     * 券类型
     *
     * Generated from protobuf field <code>string voucher_type = 4;</code>
     * @return string
     */
    public function getVoucherType()
    {
        return $this->voucher_type;
    }

    /**
     * 券类型
     *
     * Generated from protobuf field <code>string voucher_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setVoucherType($var)
    {
        GPBUtil::checkString($var, True);
        $this->voucher_type = $var;

        return $this;
    }

    /**
     * 券新版类型
     *
     * Generated from protobuf field <code>string voucher_cate = 5;</code>
     * @return string
     */
    public function getVoucherCate()
    {
        return $this->voucher_cate;
    }

    /**
     * 券新版类型
     *
     * Generated from protobuf field <code>string voucher_cate = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVoucherCate($var)
    {
        GPBUtil::checkString($var, True);
        $this->voucher_cate = $var;

        return $this;
    }

    /**
     * 用户类型
     *
     * Generated from protobuf field <code>string user_type = 6;</code>
     * @return string
     */
    public function getUserType()
    {
        return $this->user_type;
    }

    /**
     * 用户类型
     *
     * Generated from protobuf field <code>string user_type = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUserType($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_type = $var;

        return $this;
    }

    /**
     * 用户等级
     *
     * Generated from protobuf field <code>string user_level = 7;</code>
     * @return string
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * 用户等级
     *
     * Generated from protobuf field <code>string user_level = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_level = $var;

        return $this;
    }

    /**
     * 分类ID
     *
     * Generated from protobuf field <code>string category_list = 8;</code>
     * @return string
     */
    public function getCategoryList()
    {
        return $this->category_list;
    }

    /**
     * 分类ID
     *
     * Generated from protobuf field <code>string category_list = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryList($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_list = $var;

        return $this;
    }

    /**
     * 商品id
     *
     * Generated from protobuf field <code>string brand_list = 9;</code>
     * @return string
     */
    public function getBrandList()
    {
        return $this->brand_list;
    }

    /**
     * 商品id
     *
     * Generated from protobuf field <code>string brand_list = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setBrandList($var)
    {
        GPBUtil::checkString($var, True);
        $this->brand_list = $var;

        return $this;
    }

    /**
     * 关联的ID，品牌ID
     *
     * Generated from protobuf field <code>string relation_id = 10;</code>
     * @return string
     */
    public function getRelationId()
    {
        return $this->relation_id;
    }

    /**
     * 关联的ID，品牌ID
     *
     * Generated from protobuf field <code>string relation_id = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setRelationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->relation_id = $var;

        return $this;
    }

    /**
     * 商品类型
     *
     * Generated from protobuf field <code>string provider_type = 11;</code>
     * @return string
     */
    public function getProviderType()
    {
        return $this->provider_type;
    }

    /**
     * 商品类型
     *
     * Generated from protobuf field <code>string provider_type = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setProviderType($var)
    {
        GPBUtil::checkString($var, True);
        $this->provider_type = $var;

        return $this;
    }

    /**
     * 适用范围描述
     *
     * Generated from protobuf field <code>string scope_items_text = 12;</code>
     * @return string
     */
    public function getScopeItemsText()
    {
        return $this->scope_items_text;
    }

    /**
     * 适用范围描述
     *
     * Generated from protobuf field <code>string scope_items_text = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setScopeItemsText($var)
    {
        GPBUtil::checkString($var, True);
        $this->scope_items_text = $var;

        return $this;
    }

    /**
     * 在组内获取的概率百分数
     *
     * Generated from protobuf field <code>int64 rate_in_group = 13;</code>
     * @return int|string
     */
    public function getRateInGroup()
    {
        return $this->rate_in_group;
    }

    /**
     * 在组内获取的概率百分数
     *
     * Generated from protobuf field <code>int64 rate_in_group = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRateInGroup($var)
    {
        GPBUtil::checkInt64($var);
        $this->rate_in_group = $var;

        return $this;
    }

    /**
     * 使用说明
     *
     * Generated from protobuf field <code>string description = 14;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * 使用说明
     *
     * Generated from protobuf field <code>string description = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * 是否只能用于原价购买的商品
     *
     * Generated from protobuf field <code>int64 nondiscount_only = 15;</code>
     * @return int|string
     */
    public function getNondiscountOnly()
    {
        return $this->nondiscount_only;
    }

    /**
     * 是否只能用于原价购买的商品
     *
     * Generated from protobuf field <code>int64 nondiscount_only = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNondiscountOnly($var)
    {
        GPBUtil::checkInt64($var);
        $this->nondiscount_only = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 effect_position = 16;</code>
     * @return int|string
     */
    public function getEffectPosition()
    {
        return $this->effect_position;
    }

    /**
     * Generated from protobuf field <code>int64 effect_position = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEffectPosition($var)
    {
        GPBUtil::checkInt64($var);
        $this->effect_position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string effect_users = 17;</code>
     * @return string
     */
    public function getEffectUsers()
    {
        return $this->effect_users;
    }

    /**
     * Generated from protobuf field <code>string effect_users = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setEffectUsers($var)
    {
        GPBUtil::checkString($var, True);
        $this->effect_users = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 seller_support = 18;</code>
     * @return int|string
     */
    public function getSellerSupport()
    {
        return $this->seller_support;
    }

    /**
     * Generated from protobuf field <code>int64 seller_support = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSellerSupport($var)
    {
        GPBUtil::checkInt64($var);
        $this->seller_support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float condition_value = 19;</code>
     * @return float
     */
    public function getConditionValue()
    {
        return $this->condition_value;
    }

    /**
     * Generated from protobuf field <code>float condition_value = 19;</code>
     * @param float $var
     * @return $this
     */
    public function setConditionValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->condition_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float benefit_value = 20;</code>
     * @return float
     */
    public function getBenefitValue()
    {
        return $this->benefit_value;
    }

    /**
     * Generated from protobuf field <code>float benefit_value = 20;</code>
     * @param float $var
     * @return $this
     */
    public function setBenefitValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->benefit_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string code = 21;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total_count = 22;</code>
     * @return int|string
     */
    public function getTotalCount()
    {
        return $this->total_count;
    }

    /**
     * Generated from protobuf field <code>int64 total_count = 22;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 draw_count = 23;</code>
     * @return int|string
     */
    public function getDrawCount()
    {
        return $this->draw_count;
    }

    /**
     * Generated from protobuf field <code>int64 draw_count = 23;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDrawCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->draw_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string daliy_info = 24;</code>
     * @return string
     */
    public function getDaliyInfo()
    {
        return $this->daliy_info;
    }

    /**
     * Generated from protobuf field <code>string daliy_info = 24;</code>
     * @param string $var
     * @return $this
     */
    public function setDaliyInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->daliy_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 count_limited = 25;</code>
     * @return int|string
     */
    public function getCountLimited()
    {
        return $this->count_limited;
    }

    /**
     * Generated from protobuf field <code>int64 count_limited = 25;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCountLimited($var)
    {
        GPBUtil::checkInt64($var);
        $this->count_limited = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 used_count = 26;</code>
     * @return int|string
     */
    public function getUsedCount()
    {
        return $this->used_count;
    }

    /**
     * Generated from protobuf field <code>int64 used_count = 26;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUsedCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->used_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float price = 27;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>float price = 27;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 getable_time = 28;</code>
     * @return int|string
     */
    public function getGetableTime()
    {
        return $this->getable_time;
    }

    /**
     * Generated from protobuf field <code>int64 getable_time = 28;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGetableTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->getable_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 start_time = 29;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * Generated from protobuf field <code>int64 start_time = 29;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 end_time = 30;</code>
     * @return int|string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * Generated from protobuf field <code>int64 end_time = 30;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->end_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expire_days = 31;</code>
     * @return int|string
     */
    public function getExpireDays()
    {
        return $this->expire_days;
    }

    /**
     * Generated from protobuf field <code>int64 expire_days = 31;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireDays($var)
    {
        GPBUtil::checkInt64($var);
        $this->expire_days = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expire_today = 32;</code>
     * @return int|string
     */
    public function getExpireToday()
    {
        return $this->expire_today;
    }

    /**
     * Generated from protobuf field <code>int64 expire_today = 32;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireToday($var)
    {
        GPBUtil::checkInt64($var);
        $this->expire_today = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 sold_days = 33;</code>
     * @return int|string
     */
    public function getSoldDays()
    {
        return $this->sold_days;
    }

    /**
     * Generated from protobuf field <code>int64 sold_days = 33;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSoldDays($var)
    {
        GPBUtil::checkInt64($var);
        $this->sold_days = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 sold_time = 34;</code>
     * @return int|string
     */
    public function getSoldTime()
    {
        return $this->sold_time;
    }

    /**
     * Generated from protobuf field <code>int64 sold_time = 34;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSoldTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->sold_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string act_img = 35;</code>
     * @return string
     */
    public function getActImg()
    {
        return $this->act_img;
    }

    /**
     * Generated from protobuf field <code>string act_img = 35;</code>
     * @param string $var
     * @return $this
     */
    public function setActImg($var)
    {
        GPBUtil::checkString($var, True);
        $this->act_img = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 enabled = 36;</code>
     * @return int|string
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Generated from protobuf field <code>int64 enabled = 36;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkInt64($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 must_grant = 37;</code>
     * @return int|string
     */
    public function getMustGrant()
    {
        return $this->must_grant;
    }

    /**
     * Generated from protobuf field <code>int64 must_grant = 37;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMustGrant($var)
    {
        GPBUtil::checkInt64($var);
        $this->must_grant = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 create_time = 38;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * Generated from protobuf field <code>int64 create_time = 38;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->create_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 update_time = 39;</code>
     * @return int|string
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    /**
     * Generated from protobuf field <code>int64 update_time = 39;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->update_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float max_off_price = 40;</code>
     * @return float
     */
    public function getMaxOffPrice()
    {
        return $this->max_off_price;
    }

    /**
     * Generated from protobuf field <code>float max_off_price = 40;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxOffPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->max_off_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string seller_list = 41;</code>
     * @return string
     */
    public function getSellerList()
    {
        return $this->seller_list;
    }

    /**
     * Generated from protobuf field <code>string seller_list = 41;</code>
     * @param string $var
     * @return $this
     */
    public function setSellerList($var)
    {
        GPBUtil::checkString($var, True);
        $this->seller_list = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 integral = 42;</code>
     * @return int|string
     */
    public function getIntegral()
    {
        return $this->integral;
    }

    /**
     * Generated from protobuf field <code>int64 integral = 42;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntegral($var)
    {
        GPBUtil::checkInt64($var);
        $this->integral = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string skip_links = 43;</code>
     * @return string
     */
    public function getSkipLinks()
    {
        return $this->skip_links;
    }

    /**
     * Generated from protobuf field <code>string skip_links = 43;</code>
     * @param string $var
     * @return $this
     */
    public function setSkipLinks($var)
    {
        GPBUtil::checkString($var, True);
        $this->skip_links = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string activity_list = 44;</code>
     * @return string
     */
    public function getActivityList()
    {
        return $this->activity_list;
    }

    /**
     * Generated from protobuf field <code>string activity_list = 44;</code>
     * @param string $var
     * @return $this
     */
    public function setActivityList($var)
    {
        GPBUtil::checkString($var, True);
        $this->activity_list = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string product_type = 45;</code>
     * @return string
     */
    public function getProductType()
    {
        return $this->product_type;
    }

    /**
     * Generated from protobuf field <code>string product_type = 45;</code>
     * @param string $var
     * @return $this
     */
    public function setProductType($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string product_coverage = 46;</code>
     * @return string
     */
    public function getProductCoverage()
    {
        return $this->product_coverage;
    }

    /**
     * Generated from protobuf field <code>string product_coverage = 46;</code>
     * @param string $var
     * @return $this
     */
    public function setProductCoverage($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_coverage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 support_clearance = 47;</code>
     * @return int|string
     */
    public function getSupportClearance()
    {
        return $this->support_clearance;
    }

    /**
     * Generated from protobuf field <code>int64 support_clearance = 47;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSupportClearance($var)
    {
        GPBUtil::checkInt64($var);
        $this->support_clearance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string discount_ids = 48;</code>
     * @return string
     */
    public function getDiscountIds()
    {
        return $this->discount_ids;
    }

    /**
     * Generated from protobuf field <code>string discount_ids = 48;</code>
     * @param string $var
     * @return $this
     */
    public function setDiscountIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->discount_ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 can_use_days = 49;</code>
     * @return int|string
     */
    public function getCanUseDays()
    {
        return $this->can_use_days;
    }

    /**
     * Generated from protobuf field <code>int64 can_use_days = 49;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCanUseDays($var)
    {
        GPBUtil::checkInt64($var);
        $this->can_use_days = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 vc_id = 50;</code>
     * @return int|string
     */
    public function getVcId()
    {
        return $this->vc_id;
    }

    /**
     * Generated from protobuf field <code>int64 vc_id = 50;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVcId($var)
    {
        GPBUtil::checkInt64($var);
        $this->vc_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string seller_applying_config_ids = 51;</code>
     * @return string
     */
    public function getSellerApplyingConfigIds()
    {
        return $this->seller_applying_config_ids;
    }

    /**
     * Generated from protobuf field <code>string seller_applying_config_ids = 51;</code>
     * @param string $var
     * @return $this
     */
    public function setSellerApplyingConfigIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->seller_applying_config_ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string plum_config_ids = 52;</code>
     * @return string
     */
    public function getPlumConfigIds()
    {
        return $this->plum_config_ids;
    }

    /**
     * Generated from protobuf field <code>string plum_config_ids = 52;</code>
     * @param string $var
     * @return $this
     */
    public function setPlumConfigIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->plum_config_ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string page_ids = 53;</code>
     * @return string
     */
    public function getPageIds()
    {
        return $this->page_ids;
    }

    /**
     * Generated from protobuf field <code>string page_ids = 53;</code>
     * @param string $var
     * @return $this
     */
    public function setPageIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 onsale_day_min = 54;</code>
     * @return int|string
     */
    public function getOnsaleDayMin()
    {
        return $this->onsale_day_min;
    }

    /**
     * Generated from protobuf field <code>int64 onsale_day_min = 54;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOnsaleDayMin($var)
    {
        GPBUtil::checkInt64($var);
        $this->onsale_day_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 onsale_day_max = 55;</code>
     * @return int|string
     */
    public function getOnsaleDayMax()
    {
        return $this->onsale_day_max;
    }

    /**
     * Generated from protobuf field <code>int64 onsale_day_max = 55;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOnsaleDayMax($var)
    {
        GPBUtil::checkInt64($var);
        $this->onsale_day_max = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 show_float = 56;</code>
     * @return int|string
     */
    public function getShowFloat()
    {
        return $this->show_float;
    }

    /**
     * Generated from protobuf field <code>int64 show_float = 56;</code>
     * @param int|string $var
     * @return $this
     */
    public function setShowFloat($var)
    {
        GPBUtil::checkInt64($var);
        $this->show_float = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 can_notify = 57;</code>
     * @return int|string
     */
    public function getCanNotify()
    {
        return $this->can_notify;
    }

    /**
     * Generated from protobuf field <code>int64 can_notify = 57;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCanNotify($var)
    {
        GPBUtil::checkInt64($var);
        $this->can_notify = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 show_pos = 58;</code>
     * @return int|string
     */
    public function getShowPos()
    {
        return $this->show_pos;
    }

    /**
     * Generated from protobuf field <code>int64 show_pos = 58;</code>
     * @param int|string $var
     * @return $this
     */
    public function setShowPos($var)
    {
        GPBUtil::checkInt64($var);
        $this->show_pos = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 op_id = 59;</code>
     * @return int|string
     */
    public function getOpId()
    {
        return $this->op_id;
    }

    /**
     * Generated from protobuf field <code>int64 op_id = 59;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOpId($var)
    {
        GPBUtil::checkInt64($var);
        $this->op_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 version = 60;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int64 version = 60;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 is_show = 61;</code>
     * @return int|string
     */
    public function getIsShow()
    {
        return $this->is_show;
    }

    /**
     * Generated from protobuf field <code>int64 is_show = 61;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIsShow($var)
    {
        GPBUtil::checkInt64($var);
        $this->is_show = $var;

        return $this;
    }

    /**
     * 角标名称
     *
     * Generated from protobuf field <code>string mark_title = 62;</code>
     * @return string
     */
    public function getMarkTitle()
    {
        return $this->mark_title;
    }

    /**
     * 角标名称
     *
     * Generated from protobuf field <code>string mark_title = 62;</code>
     * @param string $var
     * @return $this
     */
    public function setMarkTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->mark_title = $var;

        return $this;
    }

}

