<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 优惠券库存操作
 *
 * Generated from protobuf message <code>voucher_types.VoucherStockRequest</code>
 */
class VoucherStockRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 优惠券组ID
     *
     * Generated from protobuf field <code>int64 group_id = 1;</code>
     */
    protected $group_id = 0;
    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>repeated int64 voucher_id = 2;</code>
     */
    private $voucher_id;
    /**
     * 库存数量
     *
     * Generated from protobuf field <code>int32 stock_num = 3;</code>
     */
    protected $stock_num = 0;
    /**
     * 操作类型：lock锁库存、unlock解锁库存
     *
     * Generated from protobuf field <code>string action_type = 4;</code>
     */
    protected $action_type = '';
    /**
     * 操作人员ID
     *
     * Generated from protobuf field <code>int64 op_id = 10;</code>
     */
    protected $op_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $group_id
     *           优惠券组ID
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $voucher_id
     *           优惠券ID
     *     @type int $stock_num
     *           库存数量
     *     @type string $action_type
     *           操作类型：lock锁库存、unlock解锁库存
     *     @type int|string $op_id
     *           操作人员ID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParam::initOnce();
        parent::__construct($data);
    }

    /**
     * 优惠券组ID
     *
     * Generated from protobuf field <code>int64 group_id = 1;</code>
     * @return int|string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * 优惠券组ID
     *
     * Generated from protobuf field <code>int64 group_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->group_id = $var;

        return $this;
    }

    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>repeated int64 voucher_id = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVoucherId()
    {
        return $this->voucher_id;
    }

    /**
     * 优惠券ID
     *
     * Generated from protobuf field <code>repeated int64 voucher_id = 2;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVoucherId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->voucher_id = $arr;

        return $this;
    }

    /**
     * 库存数量
     *
     * Generated from protobuf field <code>int32 stock_num = 3;</code>
     * @return int
     */
    public function getStockNum()
    {
        return $this->stock_num;
    }

    /**
     * 库存数量
     *
     * Generated from protobuf field <code>int32 stock_num = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStockNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->stock_num = $var;

        return $this;
    }

    /**
     * 操作类型：lock锁库存、unlock解锁库存
     *
     * Generated from protobuf field <code>string action_type = 4;</code>
     * @return string
     */
    public function getActionType()
    {
        return $this->action_type;
    }

    /**
     * 操作类型：lock锁库存、unlock解锁库存
     *
     * Generated from protobuf field <code>string action_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setActionType($var)
    {
        GPBUtil::checkString($var, True);
        $this->action_type = $var;

        return $this;
    }

    /**
     * 操作人员ID
     *
     * Generated from protobuf field <code>int64 op_id = 10;</code>
     * @return int|string
     */
    public function getOpId()
    {
        return $this->op_id;
    }

    /**
     * 操作人员ID
     *
     * Generated from protobuf field <code>int64 op_id = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOpId($var)
    {
        GPBUtil::checkInt64($var);
        $this->op_id = $var;

        return $this;
    }

}

