<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param-read.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * t_voucher查询条件
 *
 * Generated from protobuf message <code>voucher_types_read.VoucherWhere</code>
 */
class VoucherWhere extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int64 id = 1;</code>
     */
    private $id;
    /**
     * Generated from protobuf field <code>repeated string code = 2;</code>
     */
    private $code;
    /**
     * 1=已激活 2=未激活
     *
     * Generated from protobuf field <code>int64 enabled = 3;</code>
     */
    protected $enabled = 0;
    /**
     * 是否存在剩余 true:total_count>draw_count
     *
     * Generated from protobuf field <code>bool is_remain = 4;</code>
     */
    protected $is_remain = false;
    /**
     * user_type=?
     *
     * Generated from protobuf field <code>string user_type = 5;</code>
     */
    protected $user_type = '';
    /**
     * getable_time <= ?
     *
     * Generated from protobuf field <code>int64 getable_time_le = 6;</code>
     */
    protected $getable_time_le = 0;
    /**
     * effect_users!='new_user'
     *
     * Generated from protobuf field <code>bool no_new_user = 7;</code>
     */
    protected $no_new_user = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $id
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $code
     *     @type int|string $enabled
     *           1=已激活 2=未激活
     *     @type bool $is_remain
     *           是否存在剩余 true:total_count>draw_count
     *     @type string $user_type
     *           user_type=?
     *     @type int|string $getable_time_le
     *           getable_time <= ?
     *     @type bool $no_new_user
     *           effect_users!='new_user'
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParamRead::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int64 id = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>repeated int64 id = 1;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string code = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>repeated string code = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCode($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->code = $arr;

        return $this;
    }

    /**
     * 1=已激活 2=未激活
     *
     * Generated from protobuf field <code>int64 enabled = 3;</code>
     * @return int|string
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * 1=已激活 2=未激活
     *
     * Generated from protobuf field <code>int64 enabled = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkInt64($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * 是否存在剩余 true:total_count>draw_count
     *
     * Generated from protobuf field <code>bool is_remain = 4;</code>
     * @return bool
     */
    public function getIsRemain()
    {
        return $this->is_remain;
    }

    /**
     * 是否存在剩余 true:total_count>draw_count
     *
     * Generated from protobuf field <code>bool is_remain = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsRemain($var)
    {
        GPBUtil::checkBool($var);
        $this->is_remain = $var;

        return $this;
    }

    /**
     * user_type=?
     *
     * Generated from protobuf field <code>string user_type = 5;</code>
     * @return string
     */
    public function getUserType()
    {
        return $this->user_type;
    }

    /**
     * user_type=?
     *
     * Generated from protobuf field <code>string user_type = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUserType($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_type = $var;

        return $this;
    }

    /**
     * getable_time <= ?
     *
     * Generated from protobuf field <code>int64 getable_time_le = 6;</code>
     * @return int|string
     */
    public function getGetableTimeLe()
    {
        return $this->getable_time_le;
    }

    /**
     * getable_time <= ?
     *
     * Generated from protobuf field <code>int64 getable_time_le = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGetableTimeLe($var)
    {
        GPBUtil::checkInt64($var);
        $this->getable_time_le = $var;

        return $this;
    }

    /**
     * effect_users!='new_user'
     *
     * Generated from protobuf field <code>bool no_new_user = 7;</code>
     * @return bool
     */
    public function getNoNewUser()
    {
        return $this->no_new_user;
    }

    /**
     * effect_users!='new_user'
     *
     * Generated from protobuf field <code>bool no_new_user = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setNoNewUser($var)
    {
        GPBUtil::checkBool($var);
        $this->no_new_user = $var;

        return $this;
    }

}

