<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/voucher/voucher-param-read.proto

namespace app\components\proto\voucher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>voucher_types_read.VProductRangeConditionFields</code>
 */
class VProductRangeConditionFields extends \Google\Protobuf\Internal\Message
{
    /**
     * 定价模式：'deposit','negotiate','seller_define_price','has_floor_price','commission'
     *
     * Generated from protobuf field <code>string cooperate_type = 1;</code>
     */
    protected $cooperate_type = '';
    /**
     * 是否参加活动
     *
     * Generated from protobuf field <code>int32 is_activity = 2;</code>
     */
    protected $is_activity = 0;
    /**
     * 优惠力度
     *
     * Generated from protobuf field <code>int32 discount_capacity = 3;</code>
     */
    protected $discount_capacity = 0;
    /**
     * 商品来源：secondhand(个人卖家)、designer(合作方品牌商家)、resell(转卖)、plum(自采商品)、reclo(商家)、vip(vip卖家)、brandnew(新品)、zhongxin(众信)
     *
     * Generated from protobuf field <code>repeated string provider = 4;</code>
     */
    private $provider;
    /**
     * 商品售卖方式：plum入仓，seller挂售，oversea海外直邮
     *
     * Generated from protobuf field <code>string dispatch_type = 5;</code>
     */
    protected $dispatch_type = '';
    /**
     * 是否直播中
     *
     * Generated from protobuf field <code>int32 is_live = 6;</code>
     */
    protected $is_live = 0;
    /**
     * 是否自播
     *
     * Generated from protobuf field <code>int32 is_self_live = 7;</code>
     */
    protected $is_self_live = 0;
    /**
     * 商品参加的有效活动ID
     *
     * Generated from protobuf field <code>repeated int64 activity_id = 8;</code>
     */
    private $activity_id;
    /**
     * 卖家ID
     *
     * Generated from protobuf field <code>repeated int64 seller_id = 9;</code>
     */
    private $seller_id;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $cooperate_type
     *           定价模式：'deposit','negotiate','seller_define_price','has_floor_price','commission'
     *     @type int $is_activity
     *           是否参加活动
     *     @type int $discount_capacity
     *           优惠力度
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $provider
     *           商品来源：secondhand(个人卖家)、designer(合作方品牌商家)、resell(转卖)、plum(自采商品)、reclo(商家)、vip(vip卖家)、brandnew(新品)、zhongxin(众信)
     *     @type string $dispatch_type
     *           商品售卖方式：plum入仓，seller挂售，oversea海外直邮
     *     @type int $is_live
     *           是否直播中
     *     @type int $is_self_live
     *           是否自播
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $activity_id
     *           商品参加的有效活动ID
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $seller_id
     *           卖家ID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Voucher\VoucherParamRead::initOnce();
        parent::__construct($data);
    }

    /**
     * 定价模式：'deposit','negotiate','seller_define_price','has_floor_price','commission'
     *
     * Generated from protobuf field <code>string cooperate_type = 1;</code>
     * @return string
     */
    public function getCooperateType()
    {
        return $this->cooperate_type;
    }

    /**
     * 定价模式：'deposit','negotiate','seller_define_price','has_floor_price','commission'
     *
     * Generated from protobuf field <code>string cooperate_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCooperateType($var)
    {
        GPBUtil::checkString($var, True);
        $this->cooperate_type = $var;

        return $this;
    }

    /**
     * 是否参加活动
     *
     * Generated from protobuf field <code>int32 is_activity = 2;</code>
     * @return int
     */
    public function getIsActivity()
    {
        return $this->is_activity;
    }

    /**
     * 是否参加活动
     *
     * Generated from protobuf field <code>int32 is_activity = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIsActivity($var)
    {
        GPBUtil::checkInt32($var);
        $this->is_activity = $var;

        return $this;
    }

    /**
     * 优惠力度
     *
     * Generated from protobuf field <code>int32 discount_capacity = 3;</code>
     * @return int
     */
    public function getDiscountCapacity()
    {
        return $this->discount_capacity;
    }

    /**
     * 优惠力度
     *
     * Generated from protobuf field <code>int32 discount_capacity = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDiscountCapacity($var)
    {
        GPBUtil::checkInt32($var);
        $this->discount_capacity = $var;

        return $this;
    }

    /**
     * 商品来源：secondhand(个人卖家)、designer(合作方品牌商家)、resell(转卖)、plum(自采商品)、reclo(商家)、vip(vip卖家)、brandnew(新品)、zhongxin(众信)
     *
     * Generated from protobuf field <code>repeated string provider = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProvider()
    {
        return $this->provider;
    }

    /**
     * 商品来源：secondhand(个人卖家)、designer(合作方品牌商家)、resell(转卖)、plum(自采商品)、reclo(商家)、vip(vip卖家)、brandnew(新品)、zhongxin(众信)
     *
     * Generated from protobuf field <code>repeated string provider = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProvider($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->provider = $arr;

        return $this;
    }

    /**
     * 商品售卖方式：plum入仓，seller挂售，oversea海外直邮
     *
     * Generated from protobuf field <code>string dispatch_type = 5;</code>
     * @return string
     */
    public function getDispatchType()
    {
        return $this->dispatch_type;
    }

    /**
     * 商品售卖方式：plum入仓，seller挂售，oversea海外直邮
     *
     * Generated from protobuf field <code>string dispatch_type = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDispatchType($var)
    {
        GPBUtil::checkString($var, True);
        $this->dispatch_type = $var;

        return $this;
    }

    /**
     * 是否直播中
     *
     * Generated from protobuf field <code>int32 is_live = 6;</code>
     * @return int
     */
    public function getIsLive()
    {
        return $this->is_live;
    }

    /**
     * 是否直播中
     *
     * Generated from protobuf field <code>int32 is_live = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setIsLive($var)
    {
        GPBUtil::checkInt32($var);
        $this->is_live = $var;

        return $this;
    }

    /**
     * 是否自播
     *
     * Generated from protobuf field <code>int32 is_self_live = 7;</code>
     * @return int
     */
    public function getIsSelfLive()
    {
        return $this->is_self_live;
    }

    /**
     * 是否自播
     *
     * Generated from protobuf field <code>int32 is_self_live = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setIsSelfLive($var)
    {
        GPBUtil::checkInt32($var);
        $this->is_self_live = $var;

        return $this;
    }

    /**
     * 商品参加的有效活动ID
     *
     * Generated from protobuf field <code>repeated int64 activity_id = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActivityId()
    {
        return $this->activity_id;
    }

    /**
     * 商品参加的有效活动ID
     *
     * Generated from protobuf field <code>repeated int64 activity_id = 8;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActivityId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->activity_id = $arr;

        return $this;
    }

    /**
     * 卖家ID
     *
     * Generated from protobuf field <code>repeated int64 seller_id = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSellerId()
    {
        return $this->seller_id;
    }

    /**
     * 卖家ID
     *
     * Generated from protobuf field <code>repeated int64 seller_id = 9;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSellerId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->seller_id = $arr;

        return $this;
    }

}

